// SPDX-License-Identifier: GPL-3.0-or-later
//! Inventory icon loading — loads pre-rendered icon PNGs from assets/icons/.
//! Icons are generated by the `generate-icons` binary (real 3D screenshots).

use bevy::prelude::*;
use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat, TextureUsages};
use crate::constants::*;
use crate::types::*;
use crate::textures::load_png_texture;

/// Create a placeholder transparent icon image.
pub fn create_placeholder(images: &mut Assets<Image>) -> Handle<Image> {
    let size = Extent3d { width: ICON_SIZE, height: ICON_SIZE, depth_or_array_layers: 1 };
    images.add(Image::new_fill(size, TextureDimension::D2, &[0, 0, 0, 0],
        TextureFormat::Rgba8UnormSrgb,
        default()))
}

/// Load an icon PNG if it exists, otherwise return a placeholder.
pub fn load_icon_or_placeholder(images: &mut Assets<Image>, kind: TileKind) -> Handle<Image> {
    let name = tile_filename(kind);
    let path = format!("assets/icons/{name}.png");
    if let Ok(img) = image::open(&path) {
        let rgba = img.to_rgba8();
        let (w, h) = (rgba.width(), rgba.height());
        images.add(Image::new(
            Extent3d { width: w, height: h, depth_or_array_layers: 1 },
            TextureDimension::D2, rgba.into_raw(),
            TextureFormat::Rgba8UnormSrgb,
            default(),
        ))
    } else {
        create_placeholder(images)
    }
}

/// Build the InventoryIcons resource, loading icons from PNGs where available.
pub fn build_inventory_icons(images: &mut Assets<Image>, delete_icon: Handle<Image>) -> InventoryIcons {
    let li = |images: &mut Assets<Image>, k: TileKind| load_icon_or_placeholder(images, k);
    let li4 = |images: &mut Assets<Image>, k: fn(Direction) -> TileKind| -> [Handle<Image>; 4] {
        Direction::all().map(|d| li(images, k(d)))
    };
    InventoryIcons {
        floor: li(images, TileKind::Floor),
        source: li(images, TileKind::Source(NUM_COLORS, Direction::North)),
        goal: li(images, TileKind::Goal(NUM_COLORS)),
        turn: li(images, TileKind::Turn(NUM_COLORS, Direction::North)),
        delete: delete_icon,
        source_dir_icons: li4(images, |d| TileKind::Source(0, d)),
        source_color_icons: (0..NUM_COLORS).flat_map(|ci| Direction::all().map(move |d| TileKind::Source(ci, d)))
            .map(|k| li(images, k)).collect(),
        goal_color_icons: (0..NUM_COLORS).map(|ci| li(images, TileKind::Goal(ci))).collect(),
        turn_dir_icons: li4(images, |d| TileKind::Turn(0, d)),
        turn_color_icons: (0..NUM_TURN_COLORS).flat_map(|ci| Direction::all().map(move |d| TileKind::Turn(ci, d)))
            .map(|k| li(images, k)).collect(),
        turnbut: li(images, TileKind::TurnBut(NUM_COLORS, Direction::North)),
        turnbut_dir_icons: li4(images, |d| TileKind::TurnBut(0, d)),
        turnbut_color_icons: (0..NUM_COLORS).flat_map(|ci| Direction::all().map(move |d| TileKind::TurnBut(ci, d)))
            .map(|k| li(images, k)).collect(),
        teleport: li(images, TileKind::Teleport(NUM_COLORS, 0)),
        teleport_color_icons: (0..=NUM_COLORS).map(|ci| li(images, TileKind::Teleport(ci, 0))).collect(),
        teleportbut: li(images, TileKind::TeleportBut(NUM_COLORS, 0)),
        teleportbut_color_icons: (0..NUM_COLORS).map(|ci| li(images, TileKind::TeleportBut(ci, 0))).collect(),
        bounce: li(images, TileKind::Bounce(NUM_COLORS)),
        bounce_color_icons: (0..=NUM_COLORS).map(|ci| li(images, TileKind::Bounce(ci))).collect(),
        bouncebot: li(images, TileKind::BounceBut(NUM_COLORS)),
        bouncebot_color_icons: (0..NUM_COLORS).map(|ci| li(images, TileKind::BounceBut(ci))).collect(),
        door: li(images, TileKind::Door(false)),
        door_open: li(images, TileKind::Door(true)),
        door_closed: li(images, TileKind::Door(false)),
        switch: li(images, TileKind::Switch),
        switch_color_icons: (0..=NUM_COLORS).map(|ci| if ci == NUM_COLORS { li(images, TileKind::Switch) }
            else { li(images, TileKind::ColorSwitch(ci)) }).collect(),
        switchbut: li(images, TileKind::ColorSwitchBut(NUM_COLORS)),
        switchbut_color_icons: (0..NUM_COLORS).map(|ci| li(images, TileKind::ColorSwitchBut(ci))).collect(),
        painter: li(images, TileKind::Painter(NUM_COLORS)),
        painter_color_icons: (0..NUM_COLORS).map(|ci| li(images, TileKind::Painter(ci))).collect(),
        arrow: li(images, TileKind::Arrow(NUM_COLORS, Direction::North)),
        arrow_dir_icons: li4(images, |d| TileKind::Arrow(0, d)),
        arrow_color_icons: (0..=NUM_COLORS).flat_map(|ci| Direction::all().map(move |d| TileKind::Arrow(ci, d)))
            .map(|k| li(images, k)).collect(),
        arrowbut: li(images, TileKind::ArrowBut(NUM_COLORS, Direction::North)),
        arrowbut_dir_icons: li4(images, |d| TileKind::ArrowBut(0, d)),
        arrowbut_color_icons: (0..NUM_COLORS).flat_map(|ci| Direction::all().map(move |d| TileKind::ArrowBut(ci, d)))
            .map(|k| li(images, k)).collect(),
    }
}

pub fn tile_filename(kind: TileKind) -> String {
    match kind {
        TileKind::Floor => "floor".into(),
        TileKind::Source(ci, d) => format!("source_{ci}_{}", d.short()),
        TileKind::Goal(ci) => format!("goal_{ci}"),
        TileKind::Turn(ci, d) => format!("turn_{ci}_{}", d.short()),
        TileKind::TurnBut(ci, d) => format!("turnbut_{ci}_{}", d.short()),
        TileKind::Teleport(ci, n) => format!("teleport_{ci}_{n}"),
        TileKind::TeleportBut(ci, n) => format!("teleportbut_{ci}_{n}"),
        TileKind::Bounce(ci) => format!("bounce_{ci}"),
        TileKind::BounceBut(ci) => format!("bouncebut_{ci}"),
        TileKind::Door(o) => format!("door_{}", if o { "open" } else { "closed" }),
        TileKind::Switch => "switch".into(),
        TileKind::ColorSwitch(ci) => format!("colorswitch_{ci}"),
        TileKind::ColorSwitchBut(ci) => format!("colorswitchbut_{ci}"),
        TileKind::Painter(ci) => format!("painter_{ci}"),
        TileKind::Arrow(ci, d) => format!("arrow_{ci}_{}", d.short()),
        TileKind::ArrowBut(ci, d) => format!("arrowbut_{ci}_{}", d.short()),
        TileKind::Empty => "empty".into(),
    }
}
