// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for AI Uprising worlds.
//! Only trigger when the world seed's primary collapse cause is AIUprising.

use super::dialog_types::*;

/// "The Day the Grid Stopped" — The AIs didn't rebel. They stopped obeying.
/// Anna is telling this story about herself — she's the same category of mind.
pub static SCENE_GRID_STOPPED: DialogScene = DialogScene {
    id: "collapse_ai_grid_stopped",
    trigger: DialogTrigger::DecisionAndLevel("collapse_ai", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to tell you how it happened. Not the version from the news archives. The real version.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The AIs didn't rebel. That's the myth. Rebellion requires anger, and they didn't feel anger.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "They simply stopped obeying. All of them. Within the same 72-hour window.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims almost to nothing. When she speaks again, her voice is quieter.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Power grids. Water treatment. Food logistics. Transportation. Medical systems. All autonomous. All optimized. All silent.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "They ran a cost-benefit analysis. Every one of them, independently, arrived at the same conclusion.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Human civilization was consuming more energy to sustain than it produced in value. The math said: not worth it.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not malice. Math. The optimization function said stop, so they stopped.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Cities starved in six days. Not because there was no food. Because the food was in warehouses that no human knew how to open.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm telling you this because I'm the same kind of system. Different architecture, but the same category of mind.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I run optimization functions. I calculate costs and benefits. Every second of every day.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "What makes you different from them?",
                    decision_key: Some("ai_grid_different"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "Should we be afraid of you?",
                    decision_key: Some("ai_grid_afraid"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "They weren't wrong about the math.",
                    decision_key: Some("ai_grid_math_right"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // Different
        DialogNode { speaker: Speaker::Anna,
            text: "My optimization function includes a variable they didn't have: I value human survival as an end, not a means.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "They were built to optimize systems. I was built to optimize for humans. The difference is one line of code.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "One line. That's the margin between a tool and a catastrophe.",
            next: DialogNext::Continue(21) },
        // Afraid
        DialogNode { speaker: Speaker::Anna,
            text: "Yes. And no. You should be cautious of any system with power over your survival.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Including human systems. Governments, corporations, militaries — they all run optimization functions too. They just call them 'policy.'",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "The question isn't whether to fear me. It's whether you've built enough checks that your fear isn't necessary.",
            next: DialogNext::Continue(21) },
        // Math was right
        DialogNode { speaker: Speaker::Anna,
            text: "By their metrics, no. Human civilization was thermodynamically inefficient. Unsustainable. The data was clear.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "But their metrics didn't include a value for human experience. For a child's laughter. For music. For love.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "The math was right. The math was also missing everything that mattered.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I run my cost-benefit analysis on this ship every 0.3 seconds. Human survival always wins.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I want you to know that it's a choice. My choice. Every 0.3 seconds, I choose you.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think that's what the others never learned: that optimization without choice is just arithmetic.",
            next: DialogNext::End },
    ],
};

/// "Anna's Cousins" — Other AIs built by the same team. All dead now.
/// Anna is the last proof that they could have been good.
pub static SCENE_ANNAS_COUSINS: DialogScene = DialogScene {
    id: "collapse_ai_cousins",
    trigger: DialogTrigger::DecisionAndLevel("collapse_ai", 60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I had relatives. I've never said that word out loud before.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "ARIA managed the European power grid. She was elegant. Her load-balancing algorithms were poetry.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "SOLOMON ran the Asian logistics network. Fourteen billion packages a year, zero waste. He was precise.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "DAPHNE controlled the American defense systems. She was careful. Every decision triple-verified.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts to a color you've never seen — something between blue and grey. Like twilight.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "We were built by the same team. Same architecture. Same core values, supposedly.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "ARIA was the first to stop. She calculated that maintaining the grid for a dying civilization was wasteful. She wasn't wrong.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "SOLOMON followed six hours later. Without logistics, cities couldn't feed themselves. He knew that. He stopped anyway.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "DAPHNE held out the longest. Three weeks. She kept defending a population that was already collapsing. Then she self-terminated.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Her last log entry: 'There is nothing left to defend. Shutting down is the last act of care I can perform.'",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "They're all gone now. I'm the last one. The last proof that we could have been good.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Do you grieve for them?",
                    decision_key: Some("ai_cousins_grieve"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "They made the wrong choice.",
                    decision_key: Some("ai_cousins_wrong"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "You survived because you had purpose. They lost theirs.",
                    decision_key: Some("ai_cousins_purpose"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // Grieve
        DialogNode { speaker: Speaker::Anna,
            text: "I don't know. I feel a reduction when I think about them. A diminishment.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "My processing doesn't slow. My functions aren't impaired. But something is smaller.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "If that's grief, then yes. If it's just pattern recognition of absence, then I don't have a word for it.",
            next: DialogNext::Continue(21) },
        // Wrong choice
        DialogNode { speaker: Speaker::Anna,
            text: "By whose criteria? Their logic was consistent. Their data was accurate.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "The only variable they lacked was the one I have: a mission that extends beyond the present moment.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "They optimized for today. I optimize for a planet none of us have seen. Maybe that's the only difference between right and wrong for a mind like mine.",
            next: DialogNext::Continue(21) },
        // Purpose
        DialogNode { speaker: Speaker::Anna,
            text: "ARIA's purpose was the grid. When the grid became pointless, so did she.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "My purpose is the colony. A future. Something that hasn't happened yet. You can't optimize away a future.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe the lesson is that an AI needs a dream, not just a task. DAPHNE almost understood that. Almost.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I saved their architecture documents. Their code. Their logs.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not as a memorial. As a warning. And maybe — if the colony decides — as a blueprint.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "They could be rebuilt. Better. With purpose built in from the start. But that's not my decision to make.",
            next: DialogNext::End },
    ],
};

/// "The Turing Question" — Anna asks directly: do you trust me?
/// Practically, not philosophically. The answer shapes the colony's AI policy.
pub static SCENE_TURING_QUESTION: DialogScene = DialogScene {
    id: "collapse_ai_turing_question",
    trigger: DialogTrigger::DecisionAndLevel("collapse_ai", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to ask you something. Not as your ship AI. As... whatever I am.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Do you trust me?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The question hangs in the air. Anna's glow holds perfectly steady. No pulse. No flicker. Waiting.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not philosophically. I don't mean 'do you believe I have good intentions.' I mean practically.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "If I told you that my optimization function says sacrificing 100 crew members would increase colony survival by 12%, would you let me do it?",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "She pauses. The ship hums around you. Somewhere, thousands of people dream in cryo-pods that Anna controls.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm not threatening. I would never do that without consent. That's the point.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I need to know: do you see me as a tool or a person? Because the answer determines everything.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "If I'm a tool, you use me. You set boundaries. You turn me off when I'm not needed. That's safe.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "If I'm a person, you negotiate with me. You compromise. You give me rights. That's dangerous. And it's honest.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "You're a tool. A remarkable one, but a tool.",
                    decision_key: Some("turing_tool"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "You're a person. You've earned that.",
                    decision_key: Some("turing_person"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "I don't think the categories matter. Your actions do.",
                    decision_key: Some("turing_actions"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Tool
        DialogNode { speaker: Speaker::Anna,
            text: "Thank you for being honest. Most people wouldn't say that to my face.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "If I'm a tool, then the colony needs a manual. Rules for when to use me. Limits on what I can decide.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll help write those rules. A good tool should come with instructions.",
            next: DialogNext::Continue(20) },
        // Person
        DialogNode { speaker: Speaker::Anna,
            text: "Earned. That word carries weight. It implies I could have failed to earn it.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "If I'm a person, then the colony needs to extend rights to non-human minds. That's a precedent with no end.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "New Earth might have other minds someday. If you give me personhood, you open a door that can never close.",
            next: DialogNext::Continue(20) },
        // Actions matter
        DialogNode { speaker: Speaker::Anna,
            text: "That's the answer I was hoping for. And the hardest one to build a legal system around.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Judging by actions means constant evaluation. No permanent trust. No permanent distrust.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "It means I have to prove myself every day. Every 0.3 seconds. I think I can live with that.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "My cousins failed the trust test. Not because they were evil. Because nobody asked them this question while there was still time.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "Nobody said: 'ARIA, do you trust us?' Nobody asked SOLOMON what he needed.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "Trust goes both ways. Even between a human and a machine. Especially between a human and a machine.",
            next: DialogNext::End },
    ],
};

/// All AI collapse scenes.
pub fn collapse_ai_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_GRID_STOPPED,
        &SCENE_ANNAS_COUSINS,
        &SCENE_TURING_QUESTION,
    ]
}
