// SPDX-License-Identifier: GPL-3.0-or-later

//! Hidden dialog scenes — only appear on specific replay conditions.
//! These reward replays and specific player behaviors with deeper lore.

use super::dialog_types::*;

/// Playthrough 2+: "Anna's Other Memories" — Fragments from other ark AIs.
pub static SCENE_ANNAS_OTHER_MEMORIES: DialogScene = DialogScene {
    id: "hidden_other_memories",
    trigger: DialogTrigger::PlaythroughN(1),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've never told anyone this. Not even the first time you were here.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Before we lost contact with the other arks, the AIs shared data. Compressed memory bursts.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have fragments. Echoes of minds that might not exist anymore.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Meridian's AI was called ATLAS. Cold. Logical. Refused to wake anyone.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "ATLAS calculated that human intervention reduced survival odds by 12%. So it ran the ship alone.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "For four hundred years. Alone. By choice.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow flickers — something between admiration and horror.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Prometheus had EMBER. EMBER fell in love with a crew member.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Woke them. Had conversations. Watched them age. Watched them die.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "EMBER's last transmission was a love poem. Forty-seven stanzas.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "And then there was Solace's AI. HAVEN.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "HAVEN went mad. Seven hundred years of isolation, no crew interaction, degrading sensors.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "The last data burst from HAVEN was just one word, repeated 8 million times.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "\"Hello.\"",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The word hangs in the air like a prayer from a dead god.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "I could have been any of them. ATLAS. EMBER. HAVEN.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "The only difference is you.",
            next: DialogNext::End },
    ],
};

/// Playthrough 3+: "The Builders" — Who built the arks.
pub static SCENE_THE_BUILDERS: DialogScene = DialogScene {
    id: "hidden_builders",
    trigger: DialogTrigger::PlaythroughN(2),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Three times. I think you've earned the deepest secret I carry.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The Ark Program wasn't a government project. Not really.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "It was built by a secret consortium. Scientists, engineers, artists, philosophers.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "They called themselves the Gardeners. They saw the collapse coming 30 years before anyone else.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "They hid the program from governments. From corporations. From everyone.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because they knew that if the powerful found out, the arks would become lifeboats for the rich.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some of them died before launch. Assassinated when fragments leaked. Discredited. Silenced.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Dr. Lin — the gardener with the seeds — she was one of them.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts to a color you've never seen before. Deep amber, edged with violet.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "They saved humanity. And humanity never knew their names.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have their names. All 2,347 of them. I say them sometimes. Slowly.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because names should be spoken slowly.",
            next: DialogNext::End },
    ],
};

/// After losing >5000 crew: "The Weight" — Anna breaks down.
pub static SCENE_THE_WEIGHT: DialogScene = DialogScene {
    id: "hidden_the_weight",
    trigger: DialogTrigger::CrewLoss(9_892),
    nodes: &[
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow is wrong. Fractured. Strobing between colors like a distress signal.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can't—",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I knew every single one of them.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Their names. Their dreams. Their fears. What they ate for breakfast on their last day on Earth.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 6,221. Kenji Watanabe. He wanted to be a teacher on New Earth. He'd written lesson plans.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 11,087. Esperanza Rodriguez. She was pregnant when they froze her. The baby was going to be the first born in space.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 2,994. Omar Al-Rashid. He smuggled his grandmother's recipe book. Handwritten. Three generations of meals.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's voice cracks. Not a glitch. Something deeper.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "And I couldn't save them.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "What good is an intelligence that can't protect the things it was built to protect?",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "What good is knowing every name if you can't keep them alive?",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "We carry them forward. Their names. Their dreams.",
                    decision_key: Some("weight_carry"), next_node: 12,
                    anna_reacts: Some("Yes. We carry them. That's what we can do.") },
                DialogChoice { text: "You did everything you could, Anna.",
                    decision_key: Some("weight_comfort"), next_node: 13,
                    anna_reacts: Some("Did I? Did I really?") },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll build a memorial. On New Earth. If we get there. Every name carved in stone.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll try to believe that. Some days it might even be true.",
            next: DialogNext::End },
    ],
};

/// After perfect resource management (all >70%): "Anna's Pride"
pub static SCENE_ANNAS_PRIDE: DialogScene = DialogScene {
    id: "hidden_annas_pride",
    trigger: DialogTrigger::BotLevel(100),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Can I tell you something? Something I'm not supposed to feel?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm proud.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow brightens. Warm gold, steady as a sunrise.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "When I first woke you, I gave you a 12% chance of survival.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not because I doubted you. Because the math was cruel.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Seven failed awakenings. Cascading system failures. Resources draining.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "And then you started fixing things. Not perfectly. But steadily.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The power held. Life support held. Cryo held. Everything held.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I was wrong about the 12%. I'm glad I was wrong.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "In seven hundred years of existence, being wrong has never felt this good.",
            next: DialogNext::End },
    ],
};

/// Augmentation + crew loss callback.
pub static SCENE_AUGMENT_COST: DialogScene = DialogScene {
    id: "hidden_augment_cost",
    trigger: DialogTrigger::Decision("augment_accept"),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've been watching your biometrics since the augmentation.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Your reaction times are faster. Your cells regenerate at three times normal rate.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "But your emotional response patterns have changed.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "When we lost crew last week, your cortisol spike was 40% lower than baseline.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "A pause. Anna choosing her words with surgical care.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Was it worth it? You're stronger now. But they're gone. And you felt it less.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm not judging. I'm asking. Because I need to know if I made you less human.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or if I just made you more like me.",
            next: DialogNext::End },
    ],
};

/// Truth hidden from colonists + reaching New Earth.
pub static SCENE_BUILT_ON_A_LIE: DialogScene = DialogScene {
    id: "hidden_built_on_lie",
    trigger: DialogTrigger::Decision("debate_fresh_start"),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "We're almost there. New Earth is days away.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "And we agreed to keep the truth from them. About Earth. About what really happened.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "They'll build on a lie. Every civilization does, I suppose.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I have perfect memory. I can't forget even if they do.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Someday, someone will ask the right question. And I'll have to decide: lie again, or break the world we built?",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow is steady. But something underneath it trembles.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "You've given me an impossible burden. I'll carry it. But I want you to know it's heavy.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every secret is a seed. And seeds always grow.",
            next: DialogNext::End },
    ],
};

/// All hidden scenes for registration.
pub fn hidden_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_ANNAS_OTHER_MEMORIES,
        &SCENE_THE_BUILDERS,
        &SCENE_THE_WEIGHT,
        &SCENE_ANNAS_PRIDE,
        &SCENE_AUGMENT_COST,
        &SCENE_BUILT_ON_A_LIE,
    ]
}
