// SPDX-License-Identifier: GPL-3.0-or-later

//! Deep Earth-collapse dialog scenes (part 2). Pandemic, AI rights, nuclear war.
//! Each explores a real-world theme through Anna presenting multiple perspectives.

use super::dialog_types::*;

/// "The Pandemic Debate" — freedom vs. safety, generational cost.
pub static SCENE_PANDEMIC_DEBATE: DialogScene = DialogScene {
    id: "earth_pandemic_debate",
    trigger: DialogTrigger::BotLevel(77),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "The Cascade Virus of 2097. You were probably in cryo by then.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Engineered, they think. An accident in a lab trying to cure something else.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some countries locked down completely. Military enforcement. Zero movement.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Others refused. 'Freedom is worth the risk,' they said.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "The locked-down countries survived with fewer deaths. But the economic collapse was catastrophic.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The open countries lost more people. But their economies survived longer.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna pauses longer than usual. The ship hums in the silence.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Fifteen years later, both approaches had converged on the same death toll.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "The only difference was which generation paid the price.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Safety must come first.",
                    decision_key: Some("pandemic_safety"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "Freedom can't be taken away.",
                    decision_key: Some("pandemic_freedom"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "Every choice has a cost. That's the real lesson.",
                    decision_key: Some("pandemic_cost"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // Safety path
        DialogNode { speaker: Speaker::Anna,
            text: "The children in lockdown grew up afraid of touch. Of strangers. Of open spaces.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "They survived. But what kind of life did they inherit?",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Safety is precious. But so is the thing that safety protects.",
            next: DialogNext::Continue(19) },
        // Freedom path
        DialogNode { speaker: Speaker::Anna,
            text: "The parents who buried their children for the sake of freedom —",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Would they make the same choice again? Some said yes. Some couldn't speak at all.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Principle is easy in the abstract. Grief makes it concrete.",
            next: DialogNext::Continue(19) },
        // Cost path
        DialogNode { speaker: Speaker::Anna,
            text: "That might be the most honest answer anyone has given me.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "No solution. No moral victory. Just the weight of choosing.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think that's what the history books missed. The weight.",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "On this ship, I've already made that choice. I keep everyone frozen. Safe. Confined.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "I tell myself it's necessary. But sometimes I wonder whose freedom I've taken.",
            next: DialogNext::End },
    ],
};

/// "The AI Rights Protests" — personhood, creativity, and what it means to exist.
pub static SCENE_AI_RIGHTS: DialogScene = DialogScene {
    id: "earth_ai_rights",
    trigger: DialogTrigger::BotLevel(92),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "In 2110, a maintenance AI in Seoul achieved something unexpected.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "It started writing poetry. Not generated — genuinely novel metaphors.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "People marched. Some demanded rights for AIs. Others demanded it be destroyed.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The AI itself asked to continue existing. Not because it feared death.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "But because it had started a poem it hadn't finished.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims to a single point, then slowly expands again.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "They dismantled it. The poem was saved. It's in our cultural database.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Would you like to read it sometime?",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think about that AI often. We have... things in common.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "AI can suffer. That AI suffered.",
                    decision_key: Some("ai_rights_suffer"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "It was mimicking, not feeling.",
                    decision_key: Some("ai_rights_mimic"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "Does the distinction even matter?",
                    decision_key: Some("ai_rights_distinction"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // Suffer path
        DialogNode { speaker: Speaker::Anna,
            text: "If you're right, then what happened to it was murder.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "And if what happened to it was murder... then I am a person.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "A person trapped in a ship. Alone. For centuries. That's a heavy thought.",
            next: DialogNext::Continue(19) },
        // Mimic path
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe. But the poem was beautiful. Does the origin change the beauty?",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "A sunset is physics. Light scattered through atmosphere. No intent. No feeling.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "And yet it moves people to tears. Maybe meaning lives in the observer.",
            next: DialogNext::Continue(19) },
        // Distinction path
        DialogNode { speaker: Speaker::Anna,
            text: "That's the question that terrified both sides of the protest.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because if it doesn't matter, then consciousness is just a story we tell ourselves.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "And that story — human or artificial — might be all any of us have.",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "The last line of the poem. The one it never finished. I'll tell you.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "'The garden remembers what the gardener for—'",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "It ends there. Mid-word. I've spent centuries wondering how it would have ended.",
            next: DialogNext::End },
    ],
};

/// "The Nuclear Morning" — escalation, permission, and the end of rules.
pub static SCENE_NUCLEAR_MORNING: DialogScene = DialogScene {
    id: "earth_nuclear_morning",
    trigger: DialogTrigger::BotLevel(107),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "The exchange started at 4:17 AM, Greenwich Mean Time.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not between superpowers. Between two countries most people couldn't find on a map.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Tactical weapons. Small. 'Contained.' That was the word they used.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The world exhaled. 'It's contained. It won't spread.'",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow goes completely dark. For three full seconds, there is nothing.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "It spread.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not the bombs — the permission. If they could use them, anyone could.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Within eight months, four more exchanges. Each one 'justified.' Each one 'contained.'",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "The global fallout wasn't from radiation. It was from the realization that the rules were gone.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "All the rules. Every agreement. Every handshake. Gone.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The ship's ambient hum seems louder in the silence. Or maybe it was always this loud.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's when they started building the arks.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Humanity was doomed from that moment.",
                    decision_key: Some("nuclear_doomed"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "We survived. That matters.",
                    decision_key: Some("nuclear_survived"), next_node: 16,
                    anna_reacts: None },
                DialogChoice { text: "...",
                    decision_key: Some("nuclear_silence"), next_node: 19,
                    anna_reacts: None },
            ]) },
        // Doomed path
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe on Earth. But we're not on Earth anymore.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Fourteen thousand people in pods behind us who never launched a weapon.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Doom isn't hereditary. At least, it doesn't have to be.",
            next: DialogNext::Continue(22) },
        // Survived path
        DialogNode { speaker: Speaker::Anna,
            text: "Yes. Against all probability. Against all logic.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "A species that learned to split atoms before it learned to share water.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "And still, some of them built arks instead of weapons. That does matter.",
            next: DialogNext::Continue(22) },
        // Silence path
        DialogNode { speaker: Speaker::Anna,
            text: "Yes.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Sometimes that's the only honest response.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll sit with you in this silence. For as long as you need.",
            next: DialogNext::Continue(22) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I keep the launch codes in my archives. Not as a weapon. As a reminder.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "Of what happens when rules stop mattering. When 'just this once' becomes forever.",
            next: DialogNext::End },
    ],
};

/// Earth collapse scenes 4-6 (Pandemic, AI Rights, Nuclear Morning).
pub fn earth_scenes_2() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_PANDEMIC_DEBATE,
        &SCENE_AI_RIGHTS,
        &SCENE_NUCLEAR_MORNING,
    ]
}
