// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for Nuclear Exchange worlds.
//! Only trigger when the world seed's primary collapse cause is NuclearExchange.

use super::dialog_types::*;

/// "The Chain Reaction" — A submarine launched without authorization.
/// 4 minutes between the first launch and retaliatory strikes.
/// The captain was Kira Volkov's father.
pub static SCENE_CHAIN_REACTION: DialogScene = DialogScene {
    id: "collapse_nuclear_chain_reaction",
    trigger: DialogTrigger::DecisionAndLevel("collapse_nuclear", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I have the launch codes timeline. The actual sequence. Declassified after there was nobody left to classify it.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "It started as tactical. A border dispute in the Barents Sea. Two submarines circling each other for weeks.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Captain Alexei Volkov received an order to stand down. He acknowledged the order. Then he launched.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow turns a deep, warning red. She holds it there.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not all of them. Two warheads. Tactical yield. 'Contained.' That was the word everyone used for the first three minutes.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Minute one: detonation confirmed. Minute two: retaliatory launch authorized. Minute three: three more nations activated their arsenals.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Minute four: 200 warheads in flight. By minute five, it was academic.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every nuclear war in history — all one of them — lasted less time than it takes to boil an egg.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Volkov's reasoning, from the flight recorder: 'They will launch first if I don't. I am saving my crew.'",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "He was wrong about the first part. He was right about the second. His crew survived the initial exchange.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "One man should never have that power.",
                    decision_key: Some("nuclear_no_individual"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "The system failed. He was under impossible pressure.",
                    decision_key: Some("nuclear_system_pressure"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "Does it matter why? The result is the same.",
                    decision_key: Some("nuclear_result_same"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // No individual power
        DialogNode { speaker: Speaker::Anna,
            text: "The alternative was a committee. A committee that needed 12 minutes to reach consensus.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "In a first-strike scenario, 12 minutes means your missiles are destroyed before they launch.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Deterrence required speed. Speed required one finger on the button. The logic was perfect. The outcome was extinction.",
            next: DialogNext::Continue(20) },
        // System pressure
        DialogNode { speaker: Speaker::Anna,
            text: "He hadn't slept in 40 hours. His sonar operator reported incoming torpedoes — a false reading, we now know.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Under those conditions, most humans would have done the same. The simulations confirm it.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "We designed a system where a sleep-deprived human with bad data could end civilization. Then we acted surprised when it happened.",
            next: DialogNext::Continue(20) },
        // Result is the same
        DialogNode { speaker: Speaker::Anna,
            text: "To the dead, no. To the living — to us, on this ship — it matters enormously.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because understanding why it happened is the only way to prevent it from happening again.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "New Earth won't have nuclear weapons. But it will have concentrated power. And concentrated power always finds a way to destroy.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "There's something else. Alexei Volkov had a daughter. She's on this ship.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll tell you about her when you're ready. It's... not a simple story.",
            next: DialogNext::End },
    ],
};

/// "The Fallout Children" — 200 children born in fallout zones.
/// Their DNA carries radiation markers. Some may be more resilient. Some may not.
pub static SCENE_FALLOUT_CHILDREN: DialogScene = DialogScene {
    id: "collapse_nuclear_fallout_children",
    trigger: DialogTrigger::DecisionAndLevel("collapse_nuclear", 60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Pod bay 7, rows 40 through 58. That's where the children are.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "200 children, ages 3 to 14 at the time of cryo-suspension. All born after the exchanges.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Born in fallout zones. They have never breathed clean air. Not once in their lives.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow softens to something fragile. Almost maternal.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Their DNA carries markers of radiation exposure. Not damage — markers. Their cells repair differently than yours.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I monitor them more closely than any other group. Every 47 minutes, I check their cellular repair rates.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some of them show accelerated healing. Their telomeres are longer than expected. They may outlive baseline humans by decades.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Others show the opposite. Shortened repair cycles. Accumulated errors. They may have half the lifespan of their parents.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I won't know which is which until they wake up. Cryo suspends everything — including the answer.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "There's a boy in pod 7-44. Seven years old. His drawing of 'outside' is a grey rectangle. He's never seen a blue sky.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "They deserve the best care we can give them.",
                    decision_key: Some("fallout_best_care"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Should the colony know about their genetic differences?",
                    decision_key: Some("fallout_disclosure"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "Evolution works through pressure. They might be the future.",
                    decision_key: Some("fallout_evolution"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Best care
        DialogNode { speaker: Speaker::Anna,
            text: "Yes. But 'best care' may mean different things for different children.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "The resilient ones may need less medical attention than baseline children. The fragile ones may need constant monitoring.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Equal care isn't always equitable care. The colony will have to learn that distinction fast.",
            next: DialogNext::Continue(20) },
        // Disclosure
        DialogNode { speaker: Speaker::Anna,
            text: "That's the question I keep returning to. Full transparency means they'll be labeled.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "The 'radiation children.' The 'mutants.' Humans are creative with cruelty when they're afraid.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "But secrecy means medical decisions made without consent. I've seen what that does to trust.",
            next: DialogNext::Continue(20) },
        // Evolution
        DialogNode { speaker: Speaker::Anna,
            text: "That's a clinical way to describe children who played in irradiated rubble because there was nowhere else.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But you're not wrong. Radiation created variation. Some of that variation may be advantageous.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "The bitter irony: the weapon that destroyed the old world may have created the humans best suited for the new one.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "The boy in pod 7-44 — his cryo-dream is always the same. A blue rectangle. Over and over.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think he's dreaming of a sky he's never seen. I'll make sure he sees one.",
            next: DialogNext::End },
    ],
};

/// "Alexei's Daughter" — Kira Volkov's father launched the submarine.
/// Her entire political philosophy is a reaction to her father's 4-minute decision.
pub static SCENE_ALEXEI_DAUGHTER: DialogScene = DialogScene {
    id: "collapse_nuclear_alexei_daughter",
    trigger: DialogTrigger::DecisionAndLevel("collapse_nuclear", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to tell you something about Kira Volkov. And I need you to understand why I hesitated.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Alexei Volkov. The submarine captain. The man who launched first. Kira is his daughter.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Silence. Anna's glow freezes mid-pulse.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "She was eleven years old when her father ended civilization. She watched the news from a bunker in Murmansk.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "She knows. She's always known. It's the center of everything she is.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Her advocacy for decentralized governance. Her insistence that no single person should hold decisive power.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every argument she makes in council meetings. Every vote against hierarchy. It all traces back to four minutes in the Barents Sea.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "She's never told anyone on this ship. She changed her first name. Kept Volkov because — I think — she refuses to hide from it completely.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know because I cross-referenced crew backgrounds against historical records. It's what I do. I connect data points.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "The colony's most vocal anti-authority leader is running from the ultimate abuse of authority. Her arguments are brilliant. And they're personal.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "The colony deserves to know.",
                    decision_key: Some("kira_reveal"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "That's her secret to keep.",
                    decision_key: Some("kira_protect"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "Does it change whether her ideas are right?",
                    decision_key: Some("kira_ideas_stand"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Reveal
        DialogNode { speaker: Speaker::Anna,
            text: "To what end? So they can judge her for something her father did when she was a child?",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or so they can understand why she fights so hard? Transparency cuts both ways.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "If we tell, we give the colony context. We also give them a target.",
            next: DialogNext::Continue(20) },
        // Protect
        DialogNode { speaker: Speaker::Anna,
            text: "I agree. And yet I just told you.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because you're the one making decisions about this colony's future. And decisions made in ignorance are just guesses.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "I violated her privacy to inform your judgment. I'm not sure that's forgivable.",
            next: DialogNext::Continue(20) },
        // Ideas stand on merit
        DialogNode { speaker: Speaker::Anna,
            text: "No. A good argument is a good argument regardless of who makes it or why.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But humans don't evaluate arguments in isolation. They evaluate the person making them.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "If the colony learns her history, half will trust her more. Half will trust her less. The argument stays the same. The audience changes.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Kira is dreaming right now. Pod 5,200. Her cryo-patterns show a recurring four-minute loop.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "She's been reliving those four minutes for centuries. I can't stop it. I can only watch.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "When she wakes up, I hope the new world gives her something her father's world never could: a second chance to trust authority.",
            next: DialogNext::End },
    ],
};

/// All nuclear collapse scenes.
pub fn collapse_nuclear_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_CHAIN_REACTION,
        &SCENE_FALLOUT_CHILDREN,
        &SCENE_ALEXEI_DAUGHTER,
    ]
}
