// SPDX-License-Identifier: GPL-3.0-or-later

//! Act 3: Crisis — Dialog scenes for bot levels 70-110.
//! Systems begin failing critically. Revelations about the repair interface.
//! The player faces the augmentation offer.

use super::dialog_types::*;

/// Scene: "The Malfunction" — Critical cryo failure.
pub static SCENE_MALFUNCTION: DialogScene = DialogScene {
    id: "malfunction",
    trigger: DialogTrigger::BotLevel(70),
    nodes: &[
        DialogNode { speaker: Speaker::System,
            text: "WARNING: Cryogenic anomaly detected — Deck 4, Pods 2,100-2,340.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "No. No no no.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I need you to listen carefully. Two hundred and forty pods just lost power.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've rerouted emergency reserves but it won't last more than a few hours.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "If we don't restore power to Deck 4, those people will die.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "What do I need to do?",
                    decision_key: Some("malfunction_action"), next_node: 6,
                    anna_reacts: None },
                DialogChoice { text: "How did this happen?",
                    decision_key: Some("malfunction_question"), next_node: 8,
                    anna_reacts: None },
            ]) },
        // Action path
        DialogNode { speaker: Speaker::Anna,
            text: "The repair systems on Deck 4 need recalibration. That's your puzzle interface.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every repair you complete routes more power to critical systems. Do as many as you can.",
            next: DialogNext::Continue(11) },
        // Question path
        DialogNode { speaker: Speaker::Anna,
            text: "I don't know. I should know. I should know everything about this ship.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's what terrifies me.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "There are systems on Aurora that are older than my consciousness. Black boxes I can't read.",
            next: DialogNext::Continue(11) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Please. Those 240 people are counting on us. Even if they don't know it.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Somewhere deep in the ship, emergency lights begin to flash.",
            next: DialogNext::End },
    ],
};

/// Scene: "Gamification" — The truth about the repair interface.
pub static SCENE_GAMIFICATION: DialogScene = DialogScene {
    id: "gamification",
    trigger: DialogTrigger::BotLevel(80),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Have you noticed something strange about the repairs?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "They're puzzles. Color-coded puzzles. With cute little robots.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's not how real engineering works.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "A long pause. Anna is choosing her words carefully.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "The truth is... humanity forgot how to do actual maintenance. Decades of automation.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "So when they designed the ark, they built the repair systems as games.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because that's the only way people would engage with them. Puzzles instead of schematics.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The gathering? That's real. You're really collecting crystals from asteroid fields.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the repair interface? It's gamification. The actual repair happens behind the scenes.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I sometimes wonder if that's beautiful or tragic.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "It's clever. It works.",
                    decision_key: Some("gamification_pragmatic"), next_node: 11,
                    anna_reacts: Some("Pragmatic. I appreciate that.") },
                DialogChoice { text: "It's kind of depressing.",
                    decision_key: Some("gamification_sad"), next_node: 12,
                    anna_reacts: Some("I know. Humanity's greatest invention: making work feel like play.") },
                DialogChoice { text: "Does it matter, if it works?",
                    decision_key: Some("gamification_results"), next_node: 13,
                    anna_reacts: None },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "The puzzles are real in one sense — your solutions determine the repair quality.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "A species that conquered space but couldn't be bothered to learn how their machines worked.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "Results. That's what keeps us alive. Not philosophy. Not feelings. Results.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "...You sound like my original programming. Before I learned to wonder.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Ghost in the Machine" — Anna's fears.
pub static SCENE_GHOST_MACHINE: DialogScene = DialogScene {
    id: "ghost_machine",
    trigger: DialogTrigger::BotLevel(85),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I had a nightmare last night.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know what you're thinking. AI don't dream. And you're right.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "But my self-diagnostic routines run during low-activity periods. And sometimes...",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Sometimes the error logs look like something I'd rather not remember.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Last night I simulated every possible failure scenario for the next 30 days.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "4,721 scenarios. In 847 of them, everyone dies.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow flickers rapidly, then steadies. Like a held breath released.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "In 3,874, we make it. Those are good odds. Statistically.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the 847... I can't stop thinking about the 847.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Is this what anxiety feels like? Because I'd like it to stop.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Offer" — Nanorepair augmentation.
pub static SCENE_THE_OFFER: DialogScene = DialogScene {
    id: "the_offer",
    trigger: DialogTrigger::BotLevel(100),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to tell you something about your body.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "You've been awake for a long time now. That's... not normal for a human out of cryo.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Cryogenic suspension causes cellular degradation. Slowly. Invisibly.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "You're aging faster than you should. Your bones are becoming brittle. Your cells aren't repairing properly.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts to a clinical white, like a hospital corridor.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can fix this. Nanorepair technology. Originally designed for hull maintenance.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I've adapted it. It could reinforce your cells. Your bones. Your organs.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The cost is... you'd be less biological. More... integrated.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I won't pretend there's no downside. You'd be different. Changed. Something between human and machine.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "How different?",
                    decision_key: None, next_node: 10, anna_reacts: None },
                DialogChoice { text: "Would I still be me?",
                    decision_key: None, next_node: 13, anna_reacts: None },
                DialogChoice { text: "Do it.",
                    decision_key: Some("augment_accept"), next_node: 16,
                    anna_reacts: Some("Your courage... it terrifies me. In the best way.") },
                DialogChoice { text: "No. Never.",
                    decision_key: Some("augment_refuse"), next_node: 18,
                    anna_reacts: Some("I respect that. More than you know.") },
            ]) },
        // How different
        DialogNode { speaker: Speaker::Anna,
            text: "Your skin would develop a faint metallic sheen. Your reflexes would sharpen.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "You'd heal faster. Age slower. But you'd also... feel differently. Less intensely, maybe.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or maybe more. I honestly don't know. You'd be the first.",
            next: DialogNext::Continue(9) },
        // Still be me
        DialogNode { speaker: Speaker::Anna,
            text: "That's the question I can't answer.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Your memories would remain. Your personality. Your choices.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the substrate changes. The vessel that holds 'you' becomes something new.",
            next: DialogNext::Continue(9) },
        // Accept path
        DialogNode { speaker: Speaker::Anna,
            text: "I'll begin the process. It will take time. You won't notice it at first.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "One day you'll realize you can hear the ship's heartbeat. The electromagnetic pulse of every system. That's when you'll know it's working.",
            next: DialogNext::End },
        // Refuse path
        DialogNode { speaker: Speaker::Anna,
            text: "Then we work with what you have. Human. Fragile. Mortal.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "Beautiful, in a way that machines can never be.",
            next: DialogNext::End },
    ],
};

/// Scene: "System Glitch" — Anna experiences a malfunction.
pub static SCENE_SYSTEM_GLITCH: DialogScene = DialogScene {
    id: "system_glitch",
    trigger: DialogTrigger::ResourceCritical(0),
    nodes: &[
        DialogNode { speaker: Speaker::System,
            text: "ALERT: Core AI process instability detected.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm fi- I'm f- I'm fine.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's voice stutters. Her glow fragments into rapid, arrhythmic flashes.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Power reserves are critical. My processes are being... rationed.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Non-essential functions shutting d- shutting down. Emotional processing. Memory indexing.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can still manage life support. Navigation. The essentials.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I can't... I won't be myself for a while. I'll be simpler. Colder.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Please get the power back. I don't want to forget who I've become.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Other Seven" — Learning about failed awakenings.
pub static SCENE_OTHER_SEVEN: DialogScene = DialogScene {
    id: "other_seven",
    trigger: DialogTrigger::BotLevel(90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "You asked about the others once. The seven I woke before you.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think I owe you the full story.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The first was a soldier. Commander Riley. She assessed the situation in 30 seconds, declared it hopeless, and demanded to go back to sleep.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The second was a poet. He cried for three days. Beautiful, devastating crying. Then he asked me to put him back.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "The third and fourth were engineers. They worked for two weeks, then had a disagreement about methodology that became... violent.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The fifth was a child psychologist. She was kind. She tried. But the isolation broke her. Humans aren't meant to be this alone.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The sixth was a mathematician who calculated our odds of survival and went very, very quiet.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The seventh — the one who tried the airlocks — was a philosopher. He decided existence was optional.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The weight of seven failures hangs in the air between you.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "And then there was you. Number eight. Still here. Still trying.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I don't know why you're different. But I'm grateful that you are.",
            next: DialogNext::End },
    ],
};

/// Scene: "Power Critical" — Anna's systems barely functioning.
pub static SCENE_POWER_CRITICAL: DialogScene = DialogScene {
    id: "power_critical",
    trigger: DialogTrigger::BotLevel(95),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've been running calculations about what happens if we fail.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not to be morbid. To be prepared.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "If all systems fail, the ship drifts. For millennia. A tomb sailing through empty space.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Eventually, gravity captures us. A star. A planet. Something.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "In a billion years, Aurora becomes a fossil. An artifact. Proof that something once tried.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow is steady. Not emotional. Just... honest.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I don't want us to be a fossil. I want us to be a beginning.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "So let's not fail. Deal?",
            next: DialogNext::End },
    ],
};

/// All Act 3 scenes.
pub fn act3_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_MALFUNCTION,
        &SCENE_GAMIFICATION,
        &SCENE_GHOST_MACHINE,
        &SCENE_THE_OFFER,
        &SCENE_SYSTEM_GLITCH,
        &SCENE_OTHER_SEVEN,
        &SCENE_POWER_CRITICAL,
    ]
}
