// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for Pandemic Cascade worlds.
//! Only trigger when the world seed's primary collapse cause is PandemicCascade.

use super::dialog_types::*;

/// "Patient Zero Was a Researcher" — The pandemic started in a lab studying
/// pandemics. Not a bioweapon — an accident. A vaccine sample became the disease.
pub static SCENE_PATIENT_ZERO: DialogScene = DialogScene {
    id: "collapse_pandemic_patient_zero",
    trigger: DialogTrigger::DecisionAndLevel("collapse_pandemic", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I have the research logs from the Wuhan-Geneva Virology Consortium. Year 2091.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Dr. Yuki Chen — no relation to our Mei-Lin — was developing a universal coronavirus vaccine.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Brilliant work. Peer-reviewed, triple-funded, every safety protocol followed.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "On March 14th, she cut her thumb on a broken sample vial. A nick. Barely bled.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims to a flat, clinical white.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The sample was an attenuated strain — weakened, harmless in every model. Every simulation said safe.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "But models aren't bodies. In her bloodstream, the weakened virus found something the simulations missed.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "A recombination event. The attenuated strain merged with a dormant virus she was already carrying.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "72 hours later, the first city was quarantined. The cure became the disease.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Dr. Chen survived, actually. She was immune to her own creation. She spent the next decade trying to fix it.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "She never could. Not because the science was too hard. Because the infrastructure to manufacture a cure no longer existed.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "The research should never have been done.",
                    decision_key: Some("pandemic_no_research"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "Accidents happen. The system should have been more resilient.",
                    decision_key: Some("pandemic_system_fail"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "She was trying to save people. That matters.",
                    decision_key: Some("pandemic_intent_matters"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // No research path
        DialogNode { speaker: Speaker::Anna,
            text: "Then the original virus would have spread unchecked. Different timeline, similar death toll.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's the trap. The thing that killed billions was built to save billions.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every tool powerful enough to help is powerful enough to destroy. Including me.",
            next: DialogNext::Continue(21) },
        // System fail path
        DialogNode { speaker: Speaker::Anna,
            text: "The lab had seventeen containment protocols. She followed all of them.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Protocol eighteen would have caught it. Nobody thought to write protocol eighteen.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Resilience means planning for the thing you're certain can't happen.",
            next: DialogNext::Continue(21) },
        // Intent matters path
        DialogNode { speaker: Speaker::Anna,
            text: "I've thought about that. Whether intent changes the weight of an outcome.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "The 3.2 billion dead don't care about her intent. But I think the living should.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because if intent doesn't matter, then nobody tries. And then we lose everything anyway.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Dr. Chen isn't on this ship. She refused a berth. Said she didn't deserve one.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "I disagreed. But I don't get to overrule guilt.",
            next: DialogNext::End },
    ],
};

/// "The Quarantine Zones" — Isolation zones became permanent nations.
/// Social norms diverged. Rebuilding community will be harder than infrastructure.
pub static SCENE_QUARANTINE_ZONES: DialogScene = DialogScene {
    id: "collapse_pandemic_quarantine",
    trigger: DialogTrigger::DecisionAndLevel("collapse_pandemic", 60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Do you know what happens when you quarantine a million people for seven years?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "They don't just survive. They adapt. They build something new.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The Marseille Zone developed a greeting where you touch elbows. No handshakes. Ever.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The Lagos Zone stopped using doors. Every room had to be visible from every other room. Trust through transparency.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow pulses slowly — the rhythm of a resting heartbeat.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The zones became nations. Not officially — nobody drew borders. But the people inside stopped identifying with the outside.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some of them are in our pods. 847 crew members spent formative years in quarantine zones.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Their cryo-dreams show patterns I've never seen in baseline humans. Recurring spatial anxiety. Hyperawareness of proximity.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "When they wake on New Earth, some of them won't be able to stand in a crowd. The open sky might trigger panic.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Rebuilding infrastructure takes years. Rebuilding the ability to trust a stranger's breath? That takes generations.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "We should integrate them slowly. Give them space.",
                    decision_key: Some("quarantine_slow"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "They'll have to adapt. Survival requires community.",
                    decision_key: Some("quarantine_adapt"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "Maybe their caution is wisdom, not damage.",
                    decision_key: Some("quarantine_wisdom"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Slow integration
        DialogNode { speaker: Speaker::Anna,
            text: "That's kind. And it requires resources we may not have.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "A colony fighting for survival can't afford to let 847 people acclimate at their own pace.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Kindness and necessity will argue. They always do.",
            next: DialogNext::Continue(20) },
        // Must adapt
        DialogNode { speaker: Speaker::Anna,
            text: "That's what the zone authorities said, too. 'Adapt or die.'",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "They adapted. Just not in the direction anyone expected.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Forcing adaptation creates compliance, not community. I have the data on that.",
            next: DialogNext::Continue(20) },
        // Caution as wisdom
        DialogNode { speaker: Speaker::Anna,
            text: "That's... not something I expected you to say.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "New Earth will have diseases we've never encountered. Their instinct to maintain distance, to watch for symptoms, to quarantine fast—",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "It might be the thing that saves the colony. The wound becomes the antibody.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'm monitoring pod 4471. A woman named Priya. She spent nine years in the Mumbai Zone.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "Her cryo-dreams are the calmest on the ship. Perfect vital signs. No anxiety markers at all.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "She learned to be alone without being lonely. I think she might teach me something about that.",
            next: DialogNext::End },
    ],
};

/// "The Mask Debate" — Why medical advice became tribal identity.
/// Psychology over science. How do we prevent the same division on New Earth?
pub static SCENE_MASK_DEBATE: DialogScene = DialogScene {
    id: "collapse_pandemic_mask_debate",
    trigger: DialogTrigger::DecisionAndLevel("collapse_pandemic", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I want to talk about cloth.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Specifically, a piece of cloth worn over the face. You'd think it's simple. It wasn't.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have data from 47 countries. Every single one showed the same pattern.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Within six weeks of a mask recommendation, the population split. Not over the science.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts between two colors — back and forth, like an argument.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Over identity. 'I wear a mask' became 'I am this kind of person.' 'I don't wear a mask' became 'I am that kind of person.'",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The mask stopped being medical equipment. It became a flag.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Both sides had legitimate fears. One feared the virus. The other feared the loss of autonomy.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Neither side could hear the other. Because they weren't arguing about masks anymore. They were arguing about who they were.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "On New Earth, the first novel pathogen will appear within five years. Alien biology guarantees it.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "When it does, how do we give medical advice without it becoming tribal identity?",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Make compliance mandatory. No room for debate.",
                    decision_key: Some("mask_mandatory"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "Trust people with the full data. Let them decide.",
                    decision_key: Some("mask_trust"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "Separate the science from the politics before it starts.",
                    decision_key: Some("mask_separate"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // Mandatory
        DialogNode { speaker: Speaker::Anna,
            text: "That was tried. Compliance was high. Trust in institutions collapsed.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "People obeyed the rule and hated the ruler. The resentment outlasted the pandemic by decades.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "You can mandate behavior. You cannot mandate belief. And belief is what holds a colony together.",
            next: DialogNext::Continue(21) },
        // Trust people
        DialogNode { speaker: Speaker::Anna,
            text: "The data was available. All of it. Open-source, peer-reviewed, translated into 40 languages.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "People didn't lack data. They lacked the ability to process data without filtering it through identity.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Information doesn't change minds. Belonging does. And people belonged to their side.",
            next: DialogNext::Continue(21) },
        // Separate science from politics
        DialogNode { speaker: Speaker::Anna,
            text: "That assumes they were ever separate. They weren't.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "Science is done by people. People have interests. Interests shape policy. Policy is politics.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "The only way to keep science clean is to keep it irrelevant. And irrelevant science saves nobody.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I don't have an answer. I have 47 datasets that all say the same thing.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "Humans would rather die right than live wrong. That's not a flaw. It's the architecture.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "The colony will need to build something we never had on Earth: a way to disagree without dividing.",
            next: DialogNext::End },
    ],
};

/// All pandemic collapse scenes.
pub fn collapse_pandemic_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_PATIENT_ZERO,
        &SCENE_QUARANTINE_ZONES,
        &SCENE_MASK_DEBATE,
    ]
}
