// SPDX-License-Identifier: GPL-3.0-or-later

//! Aggregates all dialog scenes from all acts.

use super::dialog_types::DialogScene;
use super::dialog_scenes_act1;
use super::dialog_scenes_act2;
use super::dialog_scenes_act3;
use super::dialog_scenes_act4;
use super::dialog_scenes_crew;
use super::dialog_scenes_crew_ng;
use super::dialog_scenes_philosophy;
use super::dialog_scenes_philosophy2;
use super::dialog_scenes_hidden;
use super::dialog_scenes_earth;
use super::dialog_scenes_earth2;
use super::dialog_scenes_anna_personal;
use super::dialog_scenes_consequences;
use super::dialog_scenes_secrets;
use super::dialog_scenes_crossref;
use super::dialog_scenes_crossref2;
use super::dialog_scenes_orben;
use super::dialog_scenes_characters;
use super::dialog_scenes_consequences2;
use super::dialog_scenes_viktor_arc;
use super::dialog_scenes_viktor_arc2;
use super::dialog_scenes_collapse_climate;
use super::dialog_scenes_collapse_resource;
use super::dialog_scenes_collapse_pandemic;
use super::dialog_scenes_collapse_nuclear;
use super::dialog_scenes_collapse_ai;
use super::dialog_scenes_collapse_political;
use super::dialog_scenes_collapse_economic;
use super::dialog_scenes_elena;
use super::dialog_scenes_elena2;
use super::dialog_scenes_youssef;
use super::dialog_scenes_amira_arc;
use super::dialog_scenes_amira_arc2;
use super::dialog_scenes_meilin_arc;
use super::dialog_scenes_kwame_arc;
use super::dialog_scenes_kwame_arc2;
use super::dialog_scenes_connections;
use super::dialog_scenes_connections2;
use super::dialog_scenes_ngplus;
use super::dialog_scenes_ngplus2;
use super::dialog_scenes_bright;
use super::dialog_scenes_bright2;
use super::dialog_scenes_bright3;
use super::dialog_scenes_climax;
use super::dialog_scenes_climax2;
use super::dialog_scenes_colony;
use super::dialog_scenes_colony2;
use super::dialog_scenes_resolution;
use super::dialog_scenes_daily;
use super::dialog_scenes_earth_memory;
use super::dialog_scenes_crew_daily;
use super::dialog_scenes_anna_daily;
use super::dialog_scenes_philosophy3;
use super::dialog_scenes_secrets2;
use super::dialog_scenes_arrival;

/// Return all dialog scenes from all acts.
pub fn all_scenes() -> Vec<&'static DialogScene> {
    let mut scenes = Vec::new();
    scenes.extend(dialog_scenes_act1::act1_scenes());
    scenes.extend(dialog_scenes_act2::act2_scenes());
    scenes.extend(dialog_scenes_act3::act3_scenes());
    scenes.extend(dialog_scenes_act4::act4_scenes());
    scenes.extend(dialog_scenes_crew::crew_scenes());
    scenes.extend(dialog_scenes_crew_ng::crew_ng_scenes());
    scenes.extend(dialog_scenes_philosophy::philosophy_scenes_1());
    scenes.extend(dialog_scenes_philosophy2::philosophy_scenes_2());
    scenes.extend(dialog_scenes_hidden::hidden_scenes());
    scenes.extend(dialog_scenes_earth::earth_scenes_1());
    scenes.extend(dialog_scenes_earth2::earth_scenes_2());
    scenes.extend(dialog_scenes_anna_personal::anna_personal_scenes());
    scenes.extend(dialog_scenes_consequences::consequence_scenes());
    scenes.extend(dialog_scenes_secrets::secret_scenes());
    scenes.extend(dialog_scenes_crossref::crossref_scenes());
    scenes.extend(dialog_scenes_crossref2::crossref_scenes_2());
    scenes.extend(dialog_scenes_orben::orben_scenes());
    scenes.extend(dialog_scenes_characters::character_scenes_1());
    scenes.extend(dialog_scenes_consequences2::consequence_scenes_2());
    scenes.extend(dialog_scenes_viktor_arc::viktor_arc_scenes());
    scenes.extend(dialog_scenes_viktor_arc2::viktor_arc_scenes_2());
    scenes.extend(dialog_scenes_collapse_climate::collapse_climate_scenes());
    scenes.extend(dialog_scenes_collapse_resource::collapse_resource_scenes());
    scenes.extend(dialog_scenes_collapse_pandemic::collapse_pandemic_scenes());
    scenes.extend(dialog_scenes_collapse_nuclear::collapse_nuclear_scenes());
    scenes.extend(dialog_scenes_collapse_ai::collapse_ai_scenes());
    scenes.extend(dialog_scenes_collapse_political::collapse_political_scenes());
    scenes.extend(dialog_scenes_collapse_economic::collapse_economic_scenes());
    scenes.extend(dialog_scenes_elena::elena_scenes_1());
    scenes.extend(dialog_scenes_elena2::elena_scenes_2());
    scenes.extend(dialog_scenes_youssef::youssef_scenes());
    scenes.extend(dialog_scenes_amira_arc::amira_arc_scenes_1());
    scenes.extend(dialog_scenes_amira_arc2::amira_arc_scenes_2());
    scenes.extend(dialog_scenes_meilin_arc::meilin_arc_scenes());
    scenes.extend(dialog_scenes_kwame_arc::kwame_arc_scenes());
    scenes.extend(dialog_scenes_kwame_arc2::kwame_arc_scenes_2());
    scenes.extend(dialog_scenes_connections::connection_scenes_1());
    scenes.extend(dialog_scenes_connections2::connection_scenes_2());
    scenes.extend(dialog_scenes_ngplus::ngplus_scenes());
    scenes.extend(dialog_scenes_ngplus2::ngplus2_scenes());
    scenes.extend(dialog_scenes_bright::bright_scenes_1());
    scenes.extend(dialog_scenes_bright2::bright_scenes_2());
    scenes.extend(dialog_scenes_bright3::bright_scenes_3());
    scenes.extend(dialog_scenes_climax::climax_scenes_1());
    scenes.extend(dialog_scenes_climax2::climax_scenes_2());
    scenes.extend(dialog_scenes_colony::colony_scenes_1());
    scenes.extend(dialog_scenes_colony2::colony_scenes_2());
    scenes.extend(dialog_scenes_resolution::resolution_scenes());
    scenes.extend(dialog_scenes_daily::daily_scenes());
    scenes.extend(dialog_scenes_earth_memory::earth_memory_scenes());
    scenes.extend(dialog_scenes_crew_daily::crew_daily_scenes());
    scenes.extend(dialog_scenes_anna_daily::anna_daily_scenes());
    scenes.extend(dialog_scenes_philosophy3::philosophy_scenes_3());
    scenes.extend(dialog_scenes_secrets2::secret_scenes_2());
    scenes.extend(dialog_scenes_arrival::arrival_scenes());
    scenes
}
