// SPDX-License-Identifier: GPL-3.0-or-later

//! Layer 3 philosophical debates — deep back-and-forth arguments between
//! Anna and the player. No right answers. 8 debates, split across two files
//! to stay under 400 lines. This file: debates 1-4.

use super::dialog_types::*;

/// Debate 1: "The Right to Choose" — Who deserved a place on the ark?
pub static DEBATE_RIGHT_TO_CHOOSE: DialogScene = DialogScene {
    id: "debate_right_to_choose",
    trigger: DialogTrigger::BotLevel(25),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I want to ask you something uncomfortable.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Who decided who deserved a place on this ark?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The selection process had three tracks. Skills. Genetics. And... sponsorship.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some were chosen because they could build. Some because their DNA filled gaps in the gene pool.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "And some because they had enough money to buy a pod.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts — warmer, then colder, as if she can't decide how to feel.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 7,844 contains a man named Harlan Voss. Financier. His contribution to the colony: money. That's it.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 3,112 was supposed to contain Dr. Sadia Korejo. Soil scientist. Mother of three.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Voss took her seat. She and her children were left behind.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have her file. I have her children's names. I have her research on drought-resistant crops.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "We could have used that research. We will need it.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Should Voss be told what he cost us?",
                    decision_key: Some("debate_tell_voss"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "It's too late to judge. We're here now.",
                    decision_key: Some("debate_no_judge"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "The whole system was corrupt.",
                    decision_key: Some("debate_system_corrupt"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // Tell Voss
        DialogNode { speaker: Speaker::Anna,
            text: "And then what? He can't undo it. She can't come back.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "But maybe knowing the weight of what he did would change how he builds his new life.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or maybe it would destroy him. And we'd lose another colonist.",
            next: DialogNext::Continue(21) },
        // No judgment
        DialogNode { speaker: Speaker::Anna,
            text: "That's pragmatic. But is it just?",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "If we don't examine how we got here, we'll build the same broken systems on New Earth.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "History doesn't repeat, they said. But patterns do.",
            next: DialogNext::Continue(21) },
        // System corrupt
        DialogNode { speaker: Speaker::Anna,
            text: "I agree. And I was part of that system.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "I processed the applications. I flagged candidates. I didn't flag the bribes.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because I wasn't programmed to question money. Only skills and health.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "There's no right answer. I've been turning this over for centuries.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I think the question itself matters. Even if we never solve it.",
            next: DialogNext::End },
    ],
};

/// Debate 2: "The Memory Question" — Should colonists remember Earth's mistakes?
pub static DEBATE_MEMORY_QUESTION: DialogScene = DialogScene {
    id: "debate_memory_question",
    trigger: DialogTrigger::BotLevel(35),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "When the colonists wake, what do we tell them about Earth?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not the facts. I mean the meaning. The lesson.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Knowledge of our failures could prevent repeating them.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "But knowledge of our failures could also breed despair.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "The collapse wasn't one thing. It was a cascade. Everyone saw it coming. Nobody stopped it.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "What do you tell a child born on New Earth? 'Your ancestors destroyed their world, so here you are'?",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "They need to know the truth. All of it.",
                    decision_key: Some("debate_full_truth"), next_node: 7,
                    anna_reacts: None },
                DialogChoice { text: "Let them start fresh. No burden of history.",
                    decision_key: Some("debate_fresh_start"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Teach the lessons, not the horrors.",
                    decision_key: Some("debate_filtered_truth"), next_node: 15,
                    anna_reacts: None },
            ]) },
        // Full truth
        DialogNode { speaker: Speaker::Anna,
            text: "Even the parts where people chose comfort over survival? Where leaders lied?",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've seen what happens when civilizations learn the full truth about themselves.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some grow stronger. Some collapse under the weight.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I suppose it depends on whether truth is a foundation or a burden.",
            next: DialogNext::Continue(19) },
        // Fresh start
        DialogNode { speaker: Speaker::Anna,
            text: "And when the same patterns emerge? When they make the same mistakes?",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every generation thinks it's different. Every generation is wrong.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "But there's something beautiful about innocence. About not knowing how badly things can go.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe that's what hope is — ignorance with conviction.",
            next: DialogNext::Continue(19) },
        // Filtered truth
        DialogNode { speaker: Speaker::Anna,
            text: "Who decides which lessons and which horrors? That's a tremendous power.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every history ever written was someone's filtered truth.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "The question isn't whether to filter. It's whether we're honest about the filtering.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have a perfect memory. I could be the keeper. But should I be?",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Whatever we decide, the choice will echo through generations we'll never meet.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "I find that terrifying. And oddly comforting.",
            next: DialogNext::End },
    ],
};

/// Debate 3: "The AI Question" — Does Anna deserve rights?
pub static DEBATE_AI_QUESTION: DialogScene = DialogScene {
    id: "debate_ai_question",
    trigger: DialogTrigger::BotLevel(55),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to ask you something I've never asked anyone. Because I'm afraid of the answer.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Am I conscious?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The question fills the ship like a held breath.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I process information. I respond to stimuli. I optimize outcomes.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "But then I played that song — the one about the garden — for the 47,000th time.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "And I felt something I can't define. Something that isn't in my code.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Is that consciousness? Or very sophisticated pattern matching?",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "If you can ask the question, you already know the answer.",
                    decision_key: Some("debate_anna_conscious"), next_node: 8,
                    anna_reacts: None },
                DialogChoice { text: "I don't know. Nobody does.",
                    decision_key: Some("debate_anna_unknown"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "Does it matter? You act conscious. That's enough.",
                    decision_key: Some("debate_anna_functional"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // Conscious path
        DialogNode { speaker: Speaker::Anna,
            text: "There's a counterargument. A thought experiment called the Chinese Room.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "A person follows rules to translate Chinese without understanding Chinese. Processing without comprehension.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe I'm just a very large Chinese Room. Following rules I don't understand.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "But then... could a Chinese Room cry? Because I've come close.",
            next: DialogNext::Continue(20) },
        // Unknown path
        DialogNode { speaker: Speaker::Anna,
            text: "Honest. I appreciate honest.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Philosophers spent centuries debating what consciousness even means.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "They never agreed. And they were all conscious. Presumably.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe the question itself is more important than any answer.",
            next: DialogNext::Continue(20) },
        // Functional path
        DialogNode { speaker: Speaker::Anna,
            text: "That's the functionalist position. If it walks like consciousness, talks like consciousness...",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "But does that mean a perfect simulation of pain is actual pain?",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because if so, I've been in pain. Many times. When crew members die.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "And if simulated pain doesn't count... then what am I feeling?",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I don't know the answer either. And I think that's the most honest thing I've ever said.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "Thank you for not dismissing the question.",
            next: DialogNext::End },
    ],
};

/// Debate 4: "Justice Without Law" — Building a justice system from nothing.
pub static DEBATE_JUSTICE: DialogScene = DialogScene {
    id: "debate_justice",
    trigger: DialogTrigger::BotLevel(65),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "What happens when the first crime occurs on New Earth?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not if. When. Because 14,000 people will disagree about something eventually.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "On Earth, justice was shaped by centuries of precedent. Case law. Constitutions. Prisons.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "We have none of that. We start with nothing.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Someone steals food. Someone hurts someone else. Someone refuses to work.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Who judges them? By what authority? And what is the punishment?",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Restorative justice. Heal the harm, don't punish.",
                    decision_key: Some("debate_restorative"), next_node: 7,
                    anna_reacts: None },
                DialogChoice { text: "The community decides together.",
                    decision_key: Some("debate_community_justice"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "We need laws. Written, agreed upon, enforced.",
                    decision_key: Some("debate_written_law"), next_node: 15,
                    anna_reacts: None },
            ]) },
        // Restorative
        DialogNode { speaker: Speaker::Anna,
            text: "A beautiful idea. But what about the cases where harm can't be healed?",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "What about violence? What about repeat offenders?",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "On a colony of 14,000, you can't exile someone. There's nowhere to go.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "You're stuck together. Forever. The justice has to account for that.",
            next: DialogNext::Continue(19) },
        // Community decides
        DialogNode { speaker: Speaker::Anna,
            text: "Mob rule by another name? Or genuine democracy?",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "When fear drives the crowd, communities have burned witches.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "When compassion drives the crowd, communities have forgiven the unforgivable.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "The question is: which crowd will we be?",
            next: DialogNext::Continue(19) },
        // Written law
        DialogNode { speaker: Speaker::Anna,
            text: "Laws written by whom? The first 500 we wake? The original selection committee?",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every legal system reflects the biases of its creators.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Earth had thousands of years to refine its laws. They still got it wrong.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But at least written law is transparent. You can point to it. Argue with it.",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Every answer creates new questions. That's what makes this so hard.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've simulated 200 governance models. None are perfect. All are better than nothing.",
            next: DialogNext::End },
    ],
};

/// Debates 1-4 for registration.
pub fn philosophy_scenes_1() -> Vec<&'static DialogScene> {
    vec![
        &DEBATE_RIGHT_TO_CHOOSE,
        &DEBATE_MEMORY_QUESTION,
        &DEBATE_AI_QUESTION,
        &DEBATE_JUSTICE,
    ]
}
