// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for CLIMATE COLLAPSE worlds.
//! These only trigger when the world seed's primary collapse cause is
//! ClimateCollapse, making each playthrough feel genuinely different.

use super::dialog_types::*;

/// "The Last Glacier" — Anna tells the story of this world's collapse.
/// Satellite footage, a research station on melting ice, three survivors aboard.
pub static SCENE_LAST_GLACIER: DialogScene = DialogScene {
    id: "collapse_climate_last_glacier",
    trigger: DialogTrigger::DecisionAndLevel("collapse_climate", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I want to show you something. I've been waiting until you were ready.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts to a cold, pale blue — the color of deep ice.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "This is satellite imagery. Time-lapse. The Petermann Glacier in Greenland.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The image fills your mind: white stretching to the horizon, ancient and still. Then it moves.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Ten thousand years of ice. Watch what happens in this next frame. This is one decade.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The white retreats. Cracks appear — dark veins spreading through the sheet like a disease. Water pools where none has been since before civilization.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "There was a research station on top of it. Station Petermann-7. Twelve scientists.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "They measured the ice every day. Thickness, density, flow rate. They knew the numbers.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "On March 14th, 2091, the substrate reading dropped below the evacuation threshold. They had four hours.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow pulses once — sharp, like a warning klaxon rendered in light.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "Four hours to dismantle a life's work. To carry what they could to the helicopter pad. To leave behind seventeen years of samples.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "The station sank into the ocean eight hours later. The ice had been holding it up for decades, and then it just... wasn't.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Three of those researchers are on this ship. Pods 2,204, 2,205, and 2,207.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Dr. Sigrid Halvorsen still has ice core data in her personal storage allocation. 800 megabytes of a world that no longer exists.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "They must have seen it coming.",
                    decision_key: Some("glacier_saw_it"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "Four hours isn't enough time.",
                    decision_key: Some("glacier_not_enough"), next_node: 18,
                    anna_reacts: None },
                DialogChoice { text: "Why do you keep the footage?",
                    decision_key: Some("glacier_why_keep"), next_node: 21,
                    anna_reacts: None },
            ]) },
        // Saw it coming
        DialogNode { speaker: Speaker::Anna,
            text: "They published 340 papers over seventeen years. Every one said the same thing in different words.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "The data was never the problem. The listening was the problem.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "They saw it coming the way you see a wall when you're falling. Clearly, and too late to stop.",
            next: DialogNext::Continue(24) },
        // Not enough time
        DialogNode { speaker: Speaker::Anna,
            text: "No. It wasn't. Dr. Halvorsen left her mother's photograph on her desk.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "She told me about it once, in the briefing before cryo. The only time I've seen a glaciologist cry.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Four hours. That's how long we had to grieve an entire geological era.",
            next: DialogNext::Continue(24) },
        // Why keep it
        DialogNode { speaker: Speaker::Anna,
            text: "Because forgetting is how it happened in the first place.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every generation forgot what the previous one measured. Every decade, the baseline shifted.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "If I delete this footage, in two hundred years someone will say: 'It can't have been that bad.'",
            next: DialogNext::Continue(24) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "The new planet has ice caps. I've confirmed it from the probe data.",
            next: DialogNext::Continue(25) },
        DialogNode { speaker: Speaker::Anna,
            text: "I check their measurements every week. Old habits from a dead world.",
            next: DialogNext::End },
    ],
};

/// "The Water Table" — water recycling parallel between Earth and the ship.
/// Makes the climate collapse personal through the Aurora's own systems.
pub static SCENE_WATER_TABLE: DialogScene = DialogScene {
    id: "collapse_climate_water_table",
    trigger: DialogTrigger::DecisionAndLevel("collapse_climate", 60),
    nodes: &[
        DialogNode { speaker: Speaker::System,
            text: "[WATER RECYCLING: 94.7% — NOMINAL]",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "You see that number? 94.7 percent. Every drop of water on this ship passes through the recycler and 94.7 percent comes back.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The other 5.3 percent is lost. Absorbed into filters, vented with waste heat, trapped in biofilm.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "We launched with enough surplus to lose 5.3 percent per cycle for the entire voyage. Barely.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna pulls up a graph. A long, slow decline — the ship's total water reserves over time.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "If that efficiency drops below 90 percent, we start losing water faster than the surplus can cover.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "At 85 percent, I'd have to start rationing. At 80, I'd have to start choosing who gets water and who doesn't.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Earth's water cycle was about 94 percent efficient too. Evaporation, precipitation, aquifer recharge.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Her glow flickers. Something between anger and exhaustion.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "They thought 94 percent was good enough. They built cities in deserts. Drained aquifers that took ten thousand years to fill.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "When the efficiency dropped to 89 percent, they called it a drought. At 82, they called it a crisis. At 74, they stopped calling it anything.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because by then, 'crisis' was just the normal state of the world.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Can we improve the ship's efficiency?",
                    decision_key: Some("water_improve"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "What happens if it drops here too?",
                    decision_key: Some("water_if_drops"), next_node: 16,
                    anna_reacts: None },
                DialogChoice { text: "We'll be more careful this time.",
                    decision_key: Some("water_careful"), next_node: 19,
                    anna_reacts: None },
            ]) },
        // Improve
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe. The filters degrade over time. If you keep the repair bots running well, they can maintain the system.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's what you're doing right now, actually. Every bot level you gain keeps systems like this one functional.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "It's not glamorous work. But neither was maintaining aquifers. And look what happened when people stopped.",
            next: DialogNext::Continue(22) },
        // If drops
        DialogNode { speaker: Speaker::Anna,
            text: "The math is simple and unforgiving. Below 90 percent, we lose about 400 liters per day. Permanently.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Fourteen thousand people sharing a closed system with no rivers, no rain, no ocean to draw from.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Earth had oceans and it still ran out. We have tanks. I try not to think about that comparison too often.",
            next: DialogNext::Continue(22) },
        // Careful
        DialogNode { speaker: Speaker::Anna,
            text: "That's what they said too.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The words hang in the air. Anna lets the silence do the work.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "I don't mean to be harsh. But careful is a feeling. What we need is a system. Feelings didn't save the glaciers.",
            next: DialogNext::Continue(22) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "94.7 percent. I'll keep watching that number. Every day, every cycle.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because the difference between a functioning system and a catastrophe isn't dramatic. It's decimal points.",
            next: DialogNext::End },
    ],
};

/// "The Denial Archive" — 82 years of denial, 14,000 lies catalogued.
/// Anna asks the hardest question: why couldn't humanity act?
pub static SCENE_DENIAL_ARCHIVE: DialogScene = DialogScene {
    id: "collapse_climate_denial_archive",
    trigger: DialogTrigger::DecisionAndLevel("collapse_climate", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I found something in the cultural database. I've been cataloguing it for weeks.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Speeches, articles, advertisements, interviews. All saying the same thing: it isn't happening.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "1988 to 2070. Eighty-two years of people denying what they could see with their own eyes.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna projects a counter in the corner of your vision. It climbs rapidly, ticking through thousands.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've catalogued 14,247 specific, verifiable lies. Press conferences, op-eds, funded studies designed to obscure.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "14,247. One for almost every person on this ship.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims to near-darkness. When she speaks again, her voice is quieter than you've ever heard it.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm not showing you this to assign blame. The people who said those things are dead. The world they denied is dead.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm showing you because I need to understand something. And I think you might help me.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Was it ignorance? Self-interest? Fear?",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or something else — something about human cognition that makes you unable to act on threats you can see but haven't felt yet?",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "It was money. People profited from denial.",
                    decision_key: Some("denial_money"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "Humans can't process slow disasters.",
                    decision_key: Some("denial_cognition"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "People believed what they needed to believe.",
                    decision_key: Some("denial_belief"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // Money
        DialogNode { speaker: Speaker::Anna,
            text: "The funding trails are in the archive. You're right — there were people who knew the truth and chose profit.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "But that explains the speakers, not the audience. Millions of people chose to believe them. Wanted to believe them.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "The lie was supply. But the demand — that came from somewhere deeper.",
            next: DialogNext::Continue(21) },
        // Cognition
        DialogNode { speaker: Speaker::Anna,
            text: "That's what the psychologists said. Temporal discounting. Shifting baselines. Normalcy bias.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "The brain evolved to run from tigers, not to plan for temperature changes measured in fractions of degrees per decade.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "If that's true, it means the failure wasn't moral. It was architectural. A species fighting its own wiring.",
            next: DialogNext::Continue(21) },
        // Belief
        DialogNode { speaker: Speaker::Anna,
            text: "Needed. That's the word that matters.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "If the crisis is real, then everything has to change. Your job. Your home. Your idea of what a good life looks like.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Denial wasn't about the climate. It was about protecting the self from the scale of what had to be done.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'll keep the archive. All 14,247 entries. Not as an accusation.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "As a diagnostic tool. So when we reach the new planet and someone says 'it isn't happening' about something...",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "...we'll recognize the pattern. That's all I can offer. Pattern recognition.",
            next: DialogNext::End },
    ],
};

/// All climate collapse dialog scenes.
pub fn collapse_climate_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_LAST_GLACIER,
        &SCENE_WATER_TABLE,
        &SCENE_DENIAL_ARCHIVE,
    ]
}
