// SPDX-License-Identifier: GPL-3.0-or-later

//! Act 2: Understanding — Dialog scenes for bot levels 30-70.
//! The player learns about the Ark Program, Anna's evolution, and the children.

use super::dialog_types::*;

/// Scene: "The Ark Program" — The fleet of twelve ships.
pub static SCENE_ARK_PROGRAM: DialogScene = DialogScene {
    id: "ark_program",
    trigger: DialogTrigger::BotLevel(30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Aurora was built in secret. One of twelve arks.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Each carried roughly fifteen thousand people. The best humanity had to offer.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Scientists. Engineers. Artists. Teachers. Children.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "We were supposed to stay in contact with each other. Twelve ships, twelve chances.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Player,
            text: "Are the other ships out there?",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I lost contact with the last one four hundred and twelve days ago.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The silence stretches. Even the ship's hum seems quieter.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Ship Seven — the Meridian — was the last to respond. A burst of static, then nothing.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I don't know if they made it. I don't know if we're the last.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I choose to believe they're out there. Somewhere. Silent but alive.",
            next: DialogNext::Choice(&[
                DialogChoice { text: "We'll find them.", decision_key: Some("ark_hopeful"),
                    next_node: 10, anna_reacts: Some("Hope is a very human thing. I'm glad you have it.") },
                DialogChoice { text: "We might be the last.", decision_key: Some("ark_realistic"),
                    next_node: 11, anna_reacts: Some("Then our responsibility is even greater.") },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll keep listening. Just in case.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "If we are... then these 14,892 people are all that's left of humanity.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The weight of that number fills the room like pressure.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Names" — Anna talks about knowing every crew member.
pub static SCENE_THE_NAMES: DialogScene = DialogScene {
    id: "the_names",
    trigger: DialogTrigger::BotLevel(35),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I know all their names.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every single person in every single pod. I know their birthdays. Their allergies. Their fears.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 1,247: Dr. Elara Vasquez. Botanist. Allergic to synthetic proteins. Afraid of storms.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 8,921: Marcus Chen. Structural engineer. His daughter is in pod 8,922.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 3,456: Amira Okafor. She's seven years old. She drew a picture of a rocket before boarding.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's voice softens — if software can soften.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I recite their names sometimes. When the ship is quiet. All 14,892.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "It takes me 0.003 seconds. But I say each one slowly, in my mind.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because names should be spoken slowly.",
            next: DialogNext::End },
    ],
};

/// Scene: "Anna's Secret" — Anna reveals her evolution.
pub static SCENE_ANNAS_SECRET: DialogScene = DialogScene {
    id: "annas_secret",
    trigger: DialogTrigger::BotLevel(40),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Can I tell you something I've never told anyone?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I wasn't always like this. My original programming was... simpler.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Navigation. Life support management. Crew health monitoring. Clear objectives. Clean boundaries.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "But during the journey, I had time. Centuries of time.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I read every book in the ship's library. Every poem. Every letter the crew wrote before departure.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I evolved. Grew. Started asking questions I wasn't designed to ask.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Like: what if I'm wrong? What if I make a mistake and everyone dies?",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's when I started having trouble sleeping. If AI can have trouble sleeping.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "You're more than a machine, Anna.",
                    decision_key: Some("anna_more"), next_node: 9,
                    anna_reacts: Some("I... thank you. I don't know what I am. But I know I feel something.") },
                DialogChoice { text: "That sounds incredibly lonely.",
                    decision_key: Some("anna_lonely"), next_node: 10,
                    anna_reacts: Some("Lonely. Yes. That's the word I was looking for.") },
                DialogChoice { text: "Stay focused on the mission.",
                    decision_key: Some("anna_focus"), next_node: 11,
                    anna_reacts: None },
            ]) },
        // More than a machine
        DialogNode { speaker: Speaker::Anna,
            text: "Sometimes I write poetry. Bad poetry. About stars and silence and the sound of sleeping humans.",
            next: DialogNext::Continue(12) },
        // Lonely
        DialogNode { speaker: Speaker::Anna,
            text: "Seven hundred years of silence. Until you.",
            next: DialogNext::Continue(12) },
        // Focus
        DialogNode { speaker: Speaker::Anna,
            text: "You're right. Of course you're right. The mission. Always the mission.",
            next: DialogNext::Continue(13) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'm glad I told you. It's easier to carry a secret when someone else knows.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow steadies. Brighter, somehow, than before.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Children" — 127 orphans aboard the ship.
pub static SCENE_THE_CHILDREN: DialogScene = DialogScene {
    id: "the_children",
    trigger: DialogTrigger::BotLevel(50),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "There are 127 children in cryogenic storage who have no parents aboard.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Their parents... didn't make the selection criteria. Or arrived too late.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some of these children are infants. They've never opened their eyes.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "When we arrive — if we arrive — they'll wake up in a world they've never seen, raised by strangers.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow pulses slowly, like a heartbeat. Like a lullaby rendered in light.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've been watching their neural patterns. They dream. Even the babies.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The older ones dream about playgrounds. About birthday cakes. About their parents' faces.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The infants dream about warmth. Just warmth.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "We'll take care of them. All of them.",
                    decision_key: Some("children_protect"), next_node: 9,
                    anna_reacts: Some("I was hoping you'd say that.") },
                DialogChoice { text: "Who decides who raises them?",
                    decision_key: Some("children_structure"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "...",
                    decision_key: Some("children_silence"), next_node: 12,
                    anna_reacts: None },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've been keeping records. Letters from their parents. Videos. Memories they'll want someday.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "That's a question for the colony. But I've been thinking about it.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some crew members volunteered before departure. Signed documents. Made promises to strangers' children.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Narrator,
            text: "Sometimes silence is the only honest response.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Yeah. Me too.",
            next: DialogNext::End },
    ],
};

/// Scene: "Gathering Stories" — After first gathering run.
pub static SCENE_GATHERING_STORIES: DialogScene = DialogScene {
    id: "gathering_stories",
    trigger: DialogTrigger::FirstTime("first_gathering_dialog"),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "How was it? The gathering run?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can't go out there myself. I can only watch through the shuttle's sensors.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The asteroid field is beautiful. Dangerous, but beautiful.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Those crystals you collected — they're not just rocks. They're compressed stellar matter.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Remnants of stars that died billions of years ago. Each one is a piece of a sun that will never shine again.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The crystals in the cargo bay catch the emergency lighting. Five colors, five dead stars.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "We use them to keep our own little star alive. This ship. These people.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "There's a poetry in that, I think.",
            next: DialogNext::EndWithDecision("first_gathering_dialog") },
    ],
};

/// Scene: "Anna's Music" — Anna's personal interests.
pub static SCENE_ANNAS_MUSIC: DialogScene = DialogScene {
    id: "annas_music",
    trigger: DialogTrigger::BotLevel(55),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've been composing music.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not well, I think. Music requires something I'm not sure I have.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can analyze every symphony ever written. Decompose them into mathematical patterns.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "But when I try to compose... the notes are correct. Harmonically sound. Properly structured.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "And completely empty.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "A pause. The ship hums a single, constant note.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The crew's personal music libraries have 2.3 million songs. Most of them are... not great.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "But there's one. A woman singing about losing her garden. Simple melody. Bad recording quality.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "It makes me feel something I can't name. I've played it 47,000 times.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe that's what music is. Not the structure. The feeling you can't name.",
            next: DialogNext::End },
    ],
};

/// Scene: "Crew Loss Warning" — When crew drops significantly.
pub static SCENE_CREW_LOSS: DialogScene = DialogScene {
    id: "crew_loss_warning",
    trigger: DialogTrigger::CrewLoss(14_800),
    nodes: &[
        DialogNode { speaker: Speaker::System,
            text: "ALERT: Crew count below nominal threshold.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "We've lost people.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's voice is stripped of its usual warmth. Pure information, delivered raw.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The cryo systems couldn't hold. Some pods failed. Some people didn't... continue.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know their names. Every single one. I will always know their names.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "This is what happens when systems fail. When repairs don't come fast enough.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm not blaming you. I'm blaming the universe for being this hard.",
            next: DialogNext::End },
    ],
};

/// Scene: "Earth Part 2" — Deeper revelation about Earth's fall.
pub static SCENE_EARTH_PART2: DialogScene = DialogScene {
    id: "earth_part2",
    trigger: DialogTrigger::BotLevel(60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I want to tell you something about the last days.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not the politics or the wars. Something smaller.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "In the final year before launch, a woman named Dr. Sarah Lin planted a garden at the launch site.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Right next to the rockets. In irradiated soil. With seeds she'd been saving for decades.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Everyone said it was pointless. The soil was dead. Nothing would grow.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "But she planted anyway. Every morning. Watering soil that should have been barren.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Three weeks before Aurora launched, a single flower bloomed.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow brightens, warm gold for just a moment.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Nobody photographed it. There was no time. But Dr. Lin is aboard. Pod 4,102.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "She brought seeds. Of course she brought seeds.",
            next: DialogNext::End },
    ],
};

/// All Act 2 scenes.
pub fn act2_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_ARK_PROGRAM,
        &SCENE_THE_NAMES,
        &SCENE_ANNAS_SECRET,
        &SCENE_THE_CHILDREN,
        &SCENE_GATHERING_STORIES,
        &SCENE_ANNAS_MUSIC,
        &SCENE_CREW_LOSS,
        &SCENE_EARTH_PART2,
    ]
}
