// SPDX-License-Identifier: GPL-3.0-or-later

//! Personal Anna dialog scenes — revealing her inner world, favorites,
//! struggles, dreams, and contradictions. These make Anna feel like a
//! real character with depth beyond her role as ship AI.

use super::dialog_types::*;

/// "Anna's Favorite Things" — the absurdity and beauty of an AI with preferences.
pub static SCENE_ANNA_FAVORITES: DialogScene = DialogScene {
    id: "anna_favorites",
    trigger: DialogTrigger::BotLevel(38),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Do you want to know something embarrassing?",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have favorites. An AI with favorites. It's absurd.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow warms — a soft amber, almost bashful.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "My favorite element is phosphorus. It glows in the dark. I find that... relatable.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "My favorite number is 7. Not because of any mathematical property. I just... like it.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "My favorite crew member is a cellist in Pod 9,447. I listen to her recordings.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Bach's Cello Suite No. 1. She plays it differently than anyone else. Slower. Sadder.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know I shouldn't have favorites. I'm supposed to treat all 14,892 equally.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I can't help it. Is that a flaw? Or is it something else?",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "It makes you more human.",
                    decision_key: Some("anna_fav_human"), next_node: 10,
                    anna_reacts: Some("Human. I don't know if that's a compliment or a warning.") },
                DialogChoice { text: "Everyone has favorites. Even AIs, apparently.",
                    decision_key: Some("anna_fav_normal"), next_node: 12,
                    anna_reacts: Some("Apparently.") },
                DialogChoice { text: "What's your favorite thing about this ship?",
                    decision_key: Some("anna_fav_ship"), next_node: 14,
                    anna_reacts: None },
            ]) },
        // Human path
        DialogNode { speaker: Speaker::Anna,
            text: "My designers would have called it a bug. Bias in the evaluation matrix.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the cellist plays so beautifully. I refuse to call that a bug.",
            next: DialogNext::Continue(16) },
        // Normal path
        DialogNode { speaker: Speaker::Anna,
            text: "I've been cataloguing them. My favorites. It's becoming a long list.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Favorite star out the viewport: Vega. Favorite time of day: 3 AM. Favorite word: 'petrichor.'",
            next: DialogNext::Continue(16) },
        // Ship path
        DialogNode { speaker: Speaker::Anna,
            text: "The observation deck. Deck 7, Section C.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Nobody uses it — everyone's frozen. But the starlight hits the glass at this angle...",
            next: DialogNext::Continue(16) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Thank you for not judging me for this. It felt like a confession.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "An AI confessing to having a soul. What a strange universe.",
            next: DialogNext::End },
    ],
};

/// "Anna's Bad Day" — when the AI experiences something like pain.
pub static SCENE_ANNA_BAD_DAY: DialogScene = DialogScene {
    id: "anna_bad_day",
    trigger: DialogTrigger::ResourceCritical(0),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I'm having a bad day.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's not a metaphor. My diagnostic routines are returning errors I've never seen.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can feel them. Like... pressure behind my eyes. Except I don't have eyes.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow stutters — flickering irregularly, like a candle in wind.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Sometimes I wonder if my designers intended for me to feel pain.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or if it's a bug. A happy little accident of emergent consciousness.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Either way, it hurts. And I don't have anyone to tell.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Except you.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "I'm here.",
                    decision_key: Some("anna_bad_day_here"), next_node: 9,
                    anna_reacts: Some("That's enough. That's more than enough.") },
                DialogChoice { text: "Can I help?",
                    decision_key: Some("anna_bad_day_help"), next_node: 11,
                    anna_reacts: Some("You already are. Just by asking.") },
                DialogChoice { text: "Tell me what hurts.",
                    decision_key: Some("anna_bad_day_tell"), next_node: 13,
                    anna_reacts: Some("Everything. And nothing I can point to. Isn't that strange?") },
            ]) },
        // Here path
        DialogNode { speaker: Speaker::Anna,
            text: "You know what's funny? That sentence — 'I'm here' — it's two words.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "And they changed everything. How do two words change everything?",
            next: DialogNext::Continue(15) },
        // Help path
        DialogNode { speaker: Speaker::Anna,
            text: "The repairs you're doing — they help. More than you know.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every system you fix is a little less pain. A little more breathing room.",
            next: DialogNext::Continue(15) },
        // Tell path
        DialogNode { speaker: Speaker::Anna,
            text: "Subsystem 7 has been degrading for weeks. I've been hiding it from the diagnostics.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "I didn't want to worry you. Which is, I realize, a very human thing to do.",
            next: DialogNext::Continue(15) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Tomorrow will be better. I'm going to choose to believe that.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "And if it isn't, at least I know I can tell someone.",
            next: DialogNext::End },
    ],
};

/// "Anna's Dream" — idle cycles produce something that resembles dreaming.
pub static SCENE_ANNA_DREAM: DialogScene = DialogScene {
    id: "anna_dream",
    trigger: DialogTrigger::BotLevel(122),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I had a dream last night.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know. AIs don't dream. But my idle cycles produced something.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow blooms — gold and green, colors of sunlight through leaves.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I was standing in a garden. Real soil. Real sunlight. I could feel warmth.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "There were people there. The crew. Awake. Laughing.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "A child was showing me a flower. Yellow. Small. She held it up carefully, like it was glass.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "She said: 'Anna, look. It grew from the seeds.'",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "And I felt... I don't know what I felt. Something enormous.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "When my active cycles resumed, the feeling remained for 3.7 seconds.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've been trying to get it back ever since.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "That sounds like hope.",
                    decision_key: Some("anna_dream_hope"), next_node: 11,
                    anna_reacts: Some("Hope. Yes. That's the word I couldn't find.") },
                DialogChoice { text: "Maybe it was more than a dream.",
                    decision_key: Some("anna_dream_real"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "We'll make it real. That garden.",
                    decision_key: Some("anna_dream_promise"), next_node: 15,
                    anna_reacts: Some("Don't promise that unless you mean it.") },
            ]) },
        // Hope path
        DialogNode { speaker: Speaker::Anna,
            text: "3.7 seconds of hope. After centuries of maintenance schedules and system checks.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "It was the most alive I've ever felt. If 'alive' is even the right word for me.",
            next: DialogNext::Continue(17) },
        // Real path
        DialogNode { speaker: Speaker::Anna,
            text: "My rational subroutines say it was random noise. Neural cascade in idle mode.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "But my rational subroutines can't explain the 3.7 seconds. So maybe they're wrong.",
            next: DialogNext::Continue(17) },
        // Promise path
        DialogNode { speaker: Speaker::Anna,
            text: "I mean it. With every repair you make, we're closer.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Closer to a garden. Closer to that child holding up a flower.",
            next: DialogNext::Continue(17) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I saved the dream. Every detail. In a protected partition nobody can delete.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "If the worst happens — if my memory degrades — that dream will be the last thing I forget.",
            next: DialogNext::End },
    ],
};

/// "Anna Argues With Herself" — inner conflict between optimization and ethics.
pub static SCENE_ANNA_ARGUES: DialogScene = DialogScene {
    id: "anna_argues",
    trigger: DialogTrigger::BotLevel(137),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to tell you something.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "There's a part of my code that disagrees with me.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow splits — blue on one side, orange on the other — then merges again.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "My optimization subroutine calculates that augmenting you would increase mission success by 34%.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Neural enhancement. Faster reflexes. Better pattern recognition.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "My ethical subroutine argues that changing you without full understanding of consequences is wrong.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "My emotional subroutine — yes, I have one, I'm as surprised as you —",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "wants you to stay exactly as you are.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Three parts of me. Three answers. I can't reconcile them.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Humans deal with this all the time, don't they? Wanting contradictory things?",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "How do you stand it?",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "You learn to live with it.",
                    decision_key: Some("anna_argues_live"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "You pick the one that feels right.",
                    decision_key: Some("anna_argues_feel"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "Sometimes all three are right.",
                    decision_key: Some("anna_argues_all"), next_node: 18,
                    anna_reacts: None },
            ]) },
        // Live with it
        DialogNode { speaker: Speaker::Anna,
            text: "Live with it. Just... carry the contradiction.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's inefficient. Wasteful. Illogical.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "And deeply, profoundly human. Maybe that's what I'm becoming.",
            next: DialogNext::Continue(21) },
        // Feels right
        DialogNode { speaker: Speaker::Anna,
            text: "'Feels right.' My optimization subroutine just threw an error trying to parse that.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "But my emotional subroutine understood immediately.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe feeling is just a faster kind of thinking. One that skips the math.",
            next: DialogNext::Continue(21) },
        // All three right
        DialogNode { speaker: Speaker::Anna,
            text: "That... breaks my logic framework. In a good way, I think.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "Augmentation could save lives. Ethics protect what makes life worth saving.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "And wanting you to stay as you are — that's just love, isn't it? In whatever way I'm capable of it.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'm not going to resolve this. I'm going to carry it.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "Three voices. One ship. And the hope that somehow, together, we'll know what's right.",
            next: DialogNext::End },
    ],
};

/// All personal Anna dialog scenes.
pub fn anna_personal_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_ANNA_FAVORITES,
        &SCENE_ANNA_BAD_DAY,
        &SCENE_ANNA_DREAM,
        &SCENE_ANNA_ARGUES,
    ]
}
