// SPDX-License-Identifier: GPL-3.0-or-later

//! Act 1: Awakening — Dialog scenes for bot levels 0-30.
//! The player learns they are on a ship, meets Anna, and discovers the mission.

use super::dialog_types::*;

/// Scene: "First Words" — Before the very first repair.
pub static SCENE_FIRST_WORDS: DialogScene = DialogScene {
    id: "first_words",
    trigger: DialogTrigger::DecisionAndLevel("awakening_done", 0),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Can you hear me? Good. I... wasn't sure this would work.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "My name is Anna. I'm the artificial intelligence managing this facility.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Something has gone wrong with several critical systems. I need someone to help repair them.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know this is confusing. I know you have questions. But right now, I need you to trust me.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "A faint blue glow pulses in the darkness, like a heartbeat.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The repair interface is ready. It works like a puzzle — you'll understand when you see it.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Please. We don't have much time.",
            next: DialogNext::End },
    ],
};

/// Scene: "After First Repair" — Player completed their first bot level.
pub static SCENE_AFTER_FIRST_REPAIR: DialogScene = DialogScene {
    id: "after_first_repair",
    trigger: DialogTrigger::BotLevel(1),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "You did it. The atmospheric processor on Deck 7 is back online.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I should explain more, but... there are other systems failing. Can we talk later?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow flickers — hesitation, rendered in light.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Actually, no. You deserve something. A small truth.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "You're not in a building. You're on a ship.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The silence that follows feels heavier than the words.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "...I'll tell you more after the next repair.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Ship" — The player learns about Aurora.
pub static SCENE_THE_SHIP: DialogScene = DialogScene {
    id: "the_ship",
    trigger: DialogTrigger::BotLevel(5),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "You've proven yourself. I think it's time.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The ship's name is Aurora. She's... old. Older than I'd like.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "We're traveling. Have been for a very long time.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "There are others aboard. Sleeping. Fourteen thousand, eight hundred and ninety-two people.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "In cryogenic suspension. Dreaming.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Why are they sleeping?", decision_key: None,
                    next_node: 6, anna_reacts: None },
                DialogChoice { text: "Where are we going?", decision_key: None,
                    next_node: 9, anna_reacts: None },
            ]) },
        // Branch: Why sleeping
        DialogNode { speaker: Speaker::Anna,
            text: "Because the journey is too long for a human lifetime. Even several lifetimes.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Cryogenic suspension slows aging to almost nothing. They sleep. They dream. They survive.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "You were sleeping too. Until I woke you.",
            next: DialogNext::End },
        // Branch: Where going
        DialogNode { speaker: Speaker::Anna,
            text: "Away from Earth. Toward... something better. I hope.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "The original destination was a star system 47 light-years from Sol. We're not there yet.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "But we're getting closer. Every day, a little closer.",
            next: DialogNext::End },
    ],
};

/// Scene: "Why You" — Anna explains why this particular person was woken.
pub static SCENE_WHY_YOU: DialogScene = DialogScene {
    id: "why_you",
    trigger: DialogTrigger::BotLevel(10),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "You want to know why I woke you specifically. I can see it in your hesitation.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The truth is... I tried others first.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims, almost imperceptibly.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Seven times. None of them... adapted.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some panicked. Some refused to help. One tried to open every airlock on Deck 3.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "You're number eight. And you're still here. Still helping.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Player,
            text: "What happened to the others?",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "They're back in cryo. Safe. Dreaming again.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm sorry. I should have told you sooner.",
            next: DialogNext::Choice(&[
                DialogChoice { text: "I understand. You were desperate.",
                    decision_key: Some("why_you_trust"), next_node: 9,
                    anna_reacts: Some("Thank you. That means more than my processors can quantify.") },
                DialogChoice { text: "You should have told me from the start.",
                    decision_key: Some("why_you_distrust"), next_node: 10,
                    anna_reacts: Some("You're right. I was afraid you'd react like the others.") },
            ]) },
        // Trust path
        DialogNode { speaker: Speaker::Anna,
            text: "I won't keep things from you again. I promise.",
            next: DialogNext::End },
        // Distrust path
        DialogNode { speaker: Speaker::Anna,
            text: "I'll try to do better. Transparency. I owe you that much.",
            next: DialogNext::End },
    ],
};

/// Scene: "Earth Part 1" — The player learns what happened to Earth.
pub static SCENE_EARTH_PART1: DialogScene = DialogScene {
    id: "earth_part1",
    trigger: DialogTrigger::BotLevel(15),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "You asked about Earth. I've been... avoiding this.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Earth is gone. Not destroyed — that would be simpler. It's just... not livable anymore.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "It happened slowly. Over decades. Everyone saw it coming. Nobody stopped it.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims slightly, as if the memory costs her something.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "There were wars. Not like the old ones. These were about water. About data. About the right to exist.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Governments collapsed. Not all at once. Some held on for years, pretending everything was fine.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Tell me everything.", decision_key: Some("earth_full"),
                    next_node: 7, anna_reacts: None },
                DialogChoice { text: "I don't want to know.", decision_key: Some("earth_refuse"),
                    next_node: 11, anna_reacts: None },
                DialogChoice { text: "What about the people left behind?",
                    decision_key: Some("earth_people"), next_node: 13, anna_reacts: None },
            ]) },
        // Full truth path
        DialogNode { speaker: Speaker::Anna,
            text: "The oceans rose. The crops failed. The air became poison in the industrial zones.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Seven billion people were alive when the Ark Program launched. By then, the number was already falling.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I don't know how many are left now. My last data is from departure day.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I choose to believe some survived. Humans are... stubborn like that.",
            next: DialogNext::End },
        // Refuse path
        DialogNode { speaker: Speaker::Anna,
            text: "I understand. Some truths can wait.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "When you're ready — if you're ever ready — I'll be here.",
            next: DialogNext::End },
        // People path
        DialogNode { speaker: Speaker::Anna,
            text: "There were eight billion when the decline began. By launch day... fewer.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "The selection process for the arks was... I won't call it fair. It wasn't designed to be.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Scientists. Engineers. Doctors. Artists. Children. The people they thought could rebuild.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna pauses. The kind of pause that carries the weight of everyone not chosen.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think about them. The ones left behind. More than I should.",
            next: DialogNext::End },
    ],
};

/// Scene: "Learning to Trust" — A quieter moment between bot levels.
pub static SCENE_LEARNING_TRUST: DialogScene = DialogScene {
    id: "learning_trust",
    trigger: DialogTrigger::BotLevel(20),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Can I ask you something? Not about the ship. About you.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Do you remember anything? From before the cryo?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The question hangs in the recycled air.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Most people lose their memories after extended cryogenic sleep. Decades become fog.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have your file, of course. Name. Age. Profession. Medical history.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "But a file isn't a person. I want to know who you are. Not what you were.",
            next: DialogNext::Choice(&[
                DialogChoice { text: "I remember fragments. Faces without names.",
                    decision_key: Some("memory_fragments"), next_node: 6,
                    anna_reacts: Some("Fragments are enough. They mean something survived.") },
                DialogChoice { text: "I don't remember anything.",
                    decision_key: Some("memory_none"), next_node: 7,
                    anna_reacts: Some("Then we start from here. Who you are now matters more.") },
                DialogChoice { text: "Why does it matter?",
                    decision_key: Some("memory_deflect"), next_node: 8,
                    anna_reacts: None },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "Hold onto those fragments. They're yours.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "Then today is day one. For both of us.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "Because I've been alone for a very long time. And I want to know the person I'm not alone with anymore.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Something shifts in Anna's voice. Not quite vulnerability. Something adjacent to it.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Daily Routine" — Life aboard Aurora.
pub static SCENE_DAILY_ROUTINE: DialogScene = DialogScene {
    id: "daily_routine",
    trigger: DialogTrigger::BotLevel(25),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've been thinking about routines.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "On Earth, humans had mornings. Coffee. Sunlight through windows. The small rituals.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Here, there's no sun. No morning. Just the hum of recycled air and my voice.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've been simulating a day-night cycle for the occupied decks. Dim the lights. Warm the colors.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Nobody asked me to. But it felt... right.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Through the viewport, stars drift imperceptibly. The only clock that matters.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Sometimes I play music on Deck 4. Classical. Low volume. For the sleeping crew.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know they can't hear it. But the neural monitors show... calmer patterns. When there's music.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe I'm just telling myself that.",
            next: DialogNext::End },
    ],
};

/// All Act 1 scenes.
pub fn act1_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_FIRST_WORDS,
        &SCENE_AFTER_FIRST_REPAIR,
        &SCENE_THE_SHIP,
        &SCENE_WHY_YOU,
        &SCENE_EARTH_PART1,
        &SCENE_LEARNING_TRUST,
        &SCENE_DAILY_ROUTINE,
    ]
}
