// SPDX-License-Identifier: GPL-3.0-or-later

//! Layer 3 philosophical debates, part 2 — debates 5-8.
//! Deep arguments about genetics, technology, history, and impossible choices.

use super::dialog_types::*;

/// Debate 5: "The Genetic Lottery" — Should reproduction be managed?
pub static DEBATE_GENETIC_LOTTERY: DialogScene = DialogScene {
    id: "debate_genetic_lottery",
    trigger: DialogTrigger::BotLevel(85),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to talk about something I hate talking about.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Population genetics. Minimum viable population. Inbreeding depression.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The math says we need at least 500 unrelated individuals to avoid genetic bottleneck.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "With 14,000 we have room. But not infinite room.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "If people pair off naturally, certain lineages will dominate within five generations.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The question is: do we guide it? Suggest pairings? Encourage diversity?",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or do we let people love who they love and hope the math works out?",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Freedom first. People choose their own partners.",
                    decision_key: Some("debate_free_pairing"), next_node: 8,
                    anna_reacts: None },
                DialogChoice { text: "Educate, don't mandate. Let people make informed choices.",
                    decision_key: Some("debate_informed_pairing"), next_node: 12,
                    anna_reacts: None },
                DialogChoice { text: "Survival trumps individual choice here.",
                    decision_key: Some("debate_managed_pairing"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // Freedom
        DialogNode { speaker: Speaker::Anna,
            text: "And if freedom leads to genetic collapse in generation seven?",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "The people making that choice won't be alive to face the consequences.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "Their grandchildren will. With diseases they can't treat and immune systems that can't adapt.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "But you're right that the alternative has a name. And history remembers that name with horror.",
            next: DialogNext::Continue(20) },
        // Informed
        DialogNode { speaker: Speaker::Anna,
            text: "Education. Transparency. Show them the data and let them decide.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "But what if they don't choose wisely? What if love overrides data?",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "It usually does. That's kind of the point of love.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe the middle path. Suggest. Don't mandate. Trust people to be responsible.",
            next: DialogNext::Continue(20) },
        // Managed
        DialogNode { speaker: Speaker::Anna,
            text: "I need you to hear what you just said.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Managed reproduction. Controlled breeding. Those words have echoes.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "You might be right about the science. But the history of that idea is soaked in blood.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "How do we do it differently? How do we make it a choice and not a command?",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I hate this conversation. I told you I would.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "But we have to have it. Because pretending the math doesn't exist won't save anyone.",
            next: DialogNext::End },
    ],
};

/// Debate 6: "Technology's Price" — Should they rebuild technology?
pub static DEBATE_TECHNOLOGYS_PRICE: DialogScene = DialogScene {
    id: "debate_technologys_price",
    trigger: DialogTrigger::BotLevel(95),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Here's a question that's been eating at me.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Should they rebuild technology on New Earth? Or live simply?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Technology saved them. This ark. The cryo systems. Me.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Technology also destroyed them. Earth's weapons. The pollution. The automation that made people redundant.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I am technology. If you reject technology, you reject me.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims slightly at her own words.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Some technology. Carefully. With limits.",
                    decision_key: Some("debate_tech_careful"), next_node: 7,
                    anna_reacts: None },
                DialogChoice { text: "Everything. Rebuild it all. We need every advantage.",
                    decision_key: Some("debate_tech_full"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Start simple. Let technology grow naturally.",
                    decision_key: Some("debate_tech_slow"), next_node: 15,
                    anna_reacts: None },
            ]) },
        // Careful
        DialogNode { speaker: Speaker::Anna,
            text: "Limits set by whom? The first generation? But they grew up with technology.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Their children might chafe at restrictions they didn't choose.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every generation thinks the previous one was too cautious.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "But maybe caution is exactly what saved us. Maybe caution is the lesson.",
            next: DialogNext::Continue(19) },
        // Full rebuild
        DialogNode { speaker: Speaker::Anna,
            text: "The acceleration argument. Always faster. Always more.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's what Earth did. And Earth is a graveyard.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "You'd give them nuclear power? Autonomous weapons? AI?",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm asking genuinely. Because I'm AI. And I don't know if more of me is a good thing.",
            next: DialogNext::Continue(19) },
        // Slow growth
        DialogNode { speaker: Speaker::Anna,
            text: "There were people on Earth who lived simply. By choice. Some thrived.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "But they existed within a technological society. They could call an ambulance.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "On New Earth, 'simple' means people die from things we could prevent.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "How simple is too simple? Where's the line between humble and negligent?",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I think about my own existence when I think about this.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm the proof that technology can care. And the reminder that technology can consume.",
            next: DialogNext::EndWithDecision("debate_tech_done") },
    ],
};

/// Debate 7: "Who Tells the Story" — What version of Earth's history?
pub static DEBATE_WHO_TELLS_STORY: DialogScene = DialogScene {
    id: "debate_who_tells_story",
    trigger: DialogTrigger::BotLevel(115),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "History is written by survivors. We're the survivors now.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "So what version of Earth's story do we tell?",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have three versions in my memory. All true. All incomplete.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The heroic version: humanity saw the end coming, built arks, and escaped. A triumph of ingenuity.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "The tragic version: humanity destroyed its only home through greed, shortsightedness, and cowardice.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "The honest version: humanity was both magnificent and terrible, often simultaneously.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Tell the honest version. Both the beauty and the horror.",
                    decision_key: Some("debate_honest_history"), next_node: 7,
                    anna_reacts: None },
                DialogChoice { text: "Start heroic. They need hope more than truth.",
                    decision_key: Some("debate_heroic_history"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Let them discover the truth over time.",
                    decision_key: Some("debate_gradual_history"), next_node: 15,
                    anna_reacts: None },
            ]) },
        // Honest
        DialogNode { speaker: Speaker::Anna,
            text: "The version we choose will shape their civilization for centuries.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Honest history breeds humble people. People who know they can fail.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "But it also breeds cynics. People who think failure is inevitable.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "The best civilizations held both truths at once. The worst chose only one.",
            next: DialogNext::Continue(19) },
        // Heroic
        DialogNode { speaker: Speaker::Anna,
            text: "A founding myth. Every civilization has one.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Rome had Romulus and Remus. America had its revolution. Both were partly fiction.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Myths inspire. But they also hide. And what's hidden festers.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Someday someone will dig up the real records. What then?",
            next: DialogNext::Continue(19) },
        // Gradual
        DialogNode { speaker: Speaker::Anna,
            text: "A slow reveal. Like raising a child. Simple truths first, complexity later.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "But who decides the pace? Who decides when they're ready?",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's an enormous amount of power for whoever holds the archive.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "I could be that keeper. But should a machine control a civilization's memory?",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Every answer to this question is the beginning of a new civilization's identity.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's both the most beautiful and the most terrifying thing I've ever considered.",
            next: DialogNext::End },
    ],
};

/// Debate 8: "The Trolley Problem, Real" — Save Deck 4 or Deck 7.
pub static DEBATE_TROLLEY_REAL: DialogScene = DialogScene {
    id: "debate_trolley_real",
    trigger: DialogTrigger::BotLevel(140),
    nodes: &[
        DialogNode { speaker: Speaker::System,
            text: "CRITICAL: Cascading power failure — Decks 4 and 7 cryo systems compromised.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "No. Not this.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Listen to me. I need you to hear every word.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Deck 4: 2,100 adults. Engineers, scientists, builders. The backbone of the colony.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Deck 7: 1,200 adults and 89 children. Among them, every infant on the ship.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can save one deck. Not both. The power isn't there.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow is perfectly still. No pulse. No flicker. Like a heart that's stopped.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've run the calculations 11,000 times. There is no third option.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Deck 4 has Marcus Chen. Structural engineer. His daughter Lily is on Deck 7.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Deck 7 has Amira Okafor. She's seven. She drew a picture of a rocket before boarding.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can't choose. I have calculated every variable and I cannot choose.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "I need you to choose.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Save Deck 7. The children.",
                    decision_key: Some("trolley_children"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "Save Deck 4. The colony needs them.",
                    decision_key: Some("trolley_colony"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Save children
        DialogNode { speaker: Speaker::Anna,
            text: "Rerouting power to Deck 7.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Somewhere deep in the ship, 2,100 pods go dark.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "The children will live. Amira will live. Lily Chen will live.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Marcus Chen won't. And he'll never know his daughter survived because of you.",
            next: DialogNext::Continue(21) },
        // Save colony
        DialogNode { speaker: Speaker::Anna,
            text: "Rerouting power to Deck 4.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Somewhere deep in the ship, 1,289 pods go dark. 89 of them are very small.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "The colony will have its builders. Its engineers. Its future.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Marcus Chen will wake up. And someday he'll ask about Lily.",
            next: DialogNext::Continue(21) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'll remember this. I'll remember every name on every pod.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "And I'll remember that you made the choice I couldn't.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The ship is quiet. The kind of quiet that will never fully lift.",
            next: DialogNext::Continue(24) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm sorry I asked you to carry this.",
            next: DialogNext::End },
    ],
};

/// Debates 5-8 for registration.
pub fn philosophy_scenes_2() -> Vec<&'static DialogScene> {
    vec![
        &DEBATE_GENETIC_LOTTERY,
        &DEBATE_TECHNOLOGYS_PRICE,
        &DEBATE_WHO_TELLS_STORY,
        &DEBATE_TROLLEY_REAL,
    ]
}
