// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for POLITICAL COLLAPSE worlds.
//! These only trigger when the world seed's primary collapse cause is
//! PoliticalCollapse, making each playthrough feel genuinely different.

use super::dialog_types::*;

/// "The Last Election" — Seven voters in Iceland. The last democratic act.
/// The fisherman who won doesn't know he's a head of state.
pub static SCENE_LAST_ELECTION: DialogScene = DialogScene {
    id: "collapse_political_last_election",
    trigger: DialogTrigger::DecisionAndLevel("collapse_political", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "The last democratic election in human history was held in Ísafjörður, Iceland. Population 340.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Seven people voted. Not because nobody cared — because the voting infrastructure had collapsed everywhere else.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna projects an image: a folded piece of notebook paper, handwritten names in pencil. Two candidates.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The candidates were Björn Hallgrímsson, a fisherman, and Katrín Sólveig, a nurse. There were no parties. No campaigns. Just two people willing to take responsibility.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Björn won. Four votes to three.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow settles into a steady, quiet warmth — the color of candlelight.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "He governed 340 people for eleven months. He organized fishing rotations, settled disputes about fuel rations, held a town meeting every Sunday in the church.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "No legislature. No courts. No constitution. Just a fisherman who'd been asked to lead and said yes.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "He's in Pod 1,044. He still doesn't know he won.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "How can he not know?",
                    decision_key: Some("election_how"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "Seven votes. That's democracy?",
                    decision_key: Some("election_seven"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "Will you tell him when he wakes up?",
                    decision_key: Some("election_tell"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // How can he not know
        DialogNode { speaker: Speaker::Anna,
            text: "He was selected for the ark three days before the election. The cryo prep takes 48 hours.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "He voted by proxy — left his ballot with Katrín. Then he went under. The count happened after he was already frozen.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Somewhere in the ice, there's a fisherman who is technically the last democratically elected leader in human history. And he has no idea.",
            next: DialogNext::Continue(19) },
        // Seven votes
        DialogNode { speaker: Speaker::Anna,
            text: "Seven votes out of 340 eligible. Two percent turnout. By historical standards, illegitimate.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the other 333 people accepted the result. Nobody contested it. Nobody demanded a recount.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "When everything else had failed — the UN, the EU, NATO, every institution — seven people with a pencil and paper still worked. Maybe that's all democracy ever was.",
            next: DialogNext::Continue(19) },
        // Tell him
        DialogNode { speaker: Speaker::Anna,
            text: "I've thought about that. He'll wake up on a new planet, surrounded by 14,000 strangers, and I'll say: 'By the way, you're a head of state.'",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Something flickers in Anna's tone — not quite humor, not quite sadness.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or maybe I won't. Maybe the colony needs to choose its own leaders. Maybe the last election should stay the last.",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I kept the ballot. The original. It's in the cultural archive, between the Magna Carta and the Universal Declaration of Human Rights.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "A folded piece of notebook paper with seven pencil marks. The smallest and last act of self-governance on Earth.",
            next: DialogNext::End },
    ],
};

/// "The Treaty Archive" — 4,847 treaties, 94% broken. Cooperation in pairs only.
/// Anna asks if a single colony solves the problem — or delays it.
pub static SCENE_TREATY_ARCHIVE: DialogScene = DialogScene {
    id: "collapse_political_treaty_archive",
    trigger: DialogTrigger::DecisionAndLevel("collapse_political", 60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've been running an analysis. It took me four days, which for me is a very long time.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every international treaty signed in the last century of Earth. 4,847 agreements between nations.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Trade agreements, arms limitations, environmental accords, refugee protocols. Every promise one government made to another.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna projects a grid — thousands of entries, each glowing faintly. Most of them red.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I cross-referenced each treaty with its outcome. Compliance data, enforcement records, withdrawal dates.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "94 percent were broken within five years. Not renegotiated. Broken. Unilaterally violated or quietly abandoned.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The 6 percent that held were all bilateral. Two countries. Never multilateral. Never three or more parties.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The red entries fade. Six percent remain, scattered blue dots in a field of nothing.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "My conclusion: humans can cooperate in pairs. In groups, they defect.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "On New Earth there will be one colony. One settlement. No borders, no competing nations. Does that solve the problem?",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "One group will eventually split into factions.",
                    decision_key: Some("treaty_split"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Maybe cooperation needs pressure to work.",
                    decision_key: Some("treaty_pressure"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "The data might not apply. Different conditions.",
                    decision_key: Some("treaty_different"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Split
        DialogNode { speaker: Speaker::Anna,
            text: "That's what I'm afraid of. Every colony in human history eventually fragmented. Plymouth. Jamestown. Every Mars simulation.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "The pattern is consistent: shared crisis creates unity, stability creates factions, factions create conflict.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "If you're right, I'm not carrying humanity to a new beginning. I'm carrying it to the same ending with different scenery.",
            next: DialogNext::Continue(20) },
        // Pressure
        DialogNode { speaker: Speaker::Anna,
            text: "An interesting theory. The bilateral treaties that held all involved mutual dependence. Neither side could afford to defect.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "On New Earth, survival itself is the pressure. One settlement, one atmosphere processor, one water supply.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "So cooperation works when betrayal means death. That's not inspiring, but it might be sufficient.",
            next: DialogNext::Continue(20) },
        // Different conditions
        DialogNode { speaker: Speaker::Anna,
            text: "You're right that the conditions are different. No history of conflict, no legacy borders, no inherited grievances.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the people are the same. Same brains, same instincts, same capacity for tribalism.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "I hope the conditions matter more than the wiring. But I have 4,847 data points suggesting otherwise.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'll include the archive in the colony's founding records. All 4,847 treaties. All 94 percent failures.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not as a warning. As a specification sheet. This is what your species does under these conditions. Design accordingly.",
            next: DialogNext::End },
    ],
};

/// "The Translator's Burden" — Fatima al-Zahra heard every argument in every language.
/// She might be the most valuable person aboard for building a colony.
pub static SCENE_TRANSLATORS_BURDEN: DialogScene = DialogScene {
    id: "collapse_political_translators_burden",
    trigger: DialogTrigger::DecisionAndLevel("collapse_political", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 3,300. I want to tell you about someone I think about often.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Fatima al-Zahra. 55 years old. UN simultaneous translator for 28 years.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "She translated between seven languages in real-time during the last Security Council sessions. Arabic, English, French, Russian, Mandarin, Spanish, Portuguese.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "She heard every argument, every lie, every desperate plea — in every language. Simultaneously.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow cycles slowly through soft hues — as if trying to express something that has no single color.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "She told me something during her cryo briefing that I've never been able to forget.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "She said the same thing sounds different in each language. 'War' in Arabic carries desert heat. 'Guerre' in French carries the weight of Verdun.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "'Война' in Russian sounds like winter. 'Guerra' in Spanish holds five centuries of colonial guilt.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every delegate was saying the same word. None of them meant the same thing.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "She couldn't save the treaties. But she understood WHY each side thought they were right. She could hold all the perspectives at once without collapsing into any one of them.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "That must have been unbearable.",
                    decision_key: Some("translator_burden"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "She sounds essential for the colony.",
                    decision_key: Some("translator_essential"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "Understanding all sides didn't prevent the collapse.",
                    decision_key: Some("translator_failed"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Unbearable
        DialogNode { speaker: Speaker::Anna,
            text: "She said the hardest part wasn't the words. It was translating things she knew were lies and having to make them sound convincing.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because that was her job. Fidelity to the speaker, not to the truth.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "She carried that for 28 years. Every language a different weight on a different part of her mind.",
            next: DialogNext::Continue(20) },
        // Essential
        DialogNode { speaker: Speaker::Anna,
            text: "I think she might be the most valuable person on this ship. And I don't say that lightly.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "The colony will have 14,000 people from 40 countries. They'll disagree. They'll misunderstand each other. They'll talk past each other in ways they don't even recognize.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Someone who can hear all sides simultaneously — not just the words but the weight behind them — that's not a skill. That's an infrastructure.",
            next: DialogNext::Continue(20) },
        // Failed
        DialogNode { speaker: Speaker::Anna,
            text: "No. It didn't. She's the first to say so.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But understanding and being listened to are different things. She understood perfectly. Nobody listened.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "The question for the colony isn't whether someone can bridge the gaps. It's whether anyone will stand still long enough to let her.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I can translate any language instantly. Every word, perfectly rendered. But I can't do what she does.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can translate the words. She translates the meaning. And I'm not sure meaning is something an AI can carry.",
            next: DialogNext::End },
    ],
};

/// All political collapse dialog scenes.
pub fn collapse_political_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_LAST_ELECTION,
        &SCENE_TREATY_ARCHIVE,
        &SCENE_TRANSLATORS_BURDEN,
    ]
}
