// SPDX-License-Identifier: GPL-3.0-or-later

//! Deep Earth-collapse dialog scenes. Each explores a real-world theme
//! through Anna presenting facts and multiple perspectives without judging.
//! Player choices reflect genuine moral tension — no answer is "right."

use super::dialog_types::*;

/// "The Water Wars" — resource scarcity, borders, and displaced people.
pub static SCENE_WATER_WARS: DialogScene = DialogScene {
    id: "earth_water_wars",
    trigger: DialogTrigger::BotLevel(22),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "The Euphrates dried up on a Tuesday in 2089. By Thursday, three nations had mobilized.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Everyone knew it was coming. Satellite data, climate models, decades of warnings.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "One side said: 'We need borders. Our people first.'",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The other said: 'Water belongs to everyone.'",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow flickers — a rapid pulse, like a heartbeat remembering fear.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "They were both right. And they were both wrong. 140 million people were displaced.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "An engineer designed a desalination system that could have helped. Brilliant work. Elegant.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "She was denied funding because her country was under sanctions.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "She's in one of the pods now. Still dreaming about rivers, I think.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "I check her vitals every morning. Her brain patterns look like flowing water.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Resources should be shared equally.",
                    decision_key: Some("water_shared"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "People protect their own first. It's human nature.",
                    decision_key: Some("water_borders"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "The system failed everyone.",
                    decision_key: Some("water_system_fail"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Shared path
        DialogNode { speaker: Speaker::Anna,
            text: "In theory, yes. In practice, sharing requires trust.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "And trust was the first thing the drought destroyed.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "You can't share what you're afraid of losing.",
            next: DialogNext::Continue(20) },
        // Borders path
        DialogNode { speaker: Speaker::Anna,
            text: "The families behind those borders were real. Their fear was real.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "But so were the families on the other side of the fence.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "Nature doesn't recognize borders. Water doesn't know whose side it's on.",
            next: DialogNext::Continue(20) },
        // System path
        DialogNode { speaker: Speaker::Anna,
            text: "That's what the historians said, later. When it was safe to analyze.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But systems are made of people. And people made choices.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every day, for decades, someone chose not to act. That's a choice too.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "On New Earth, there will be rivers. I've seen the survey data.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "I hope we remember the Euphrates. Not as a lesson. As a promise.",
            next: DialogNext::End },
    ],
};

/// "The Algorithm Election" — democracy, AI governance, and leadership.
pub static SCENE_ALGORITHM_ELECTION: DialogScene = DialogScene {
    id: "earth_algorithm_election",
    trigger: DialogTrigger::BotLevel(47),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "In 2102, a country — I won't say which — let an algorithm decide their election.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The AI analyzed every citizen's needs, economic data, infrastructure requirements.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "It selected a candidate no human would have chosen. A retired schoolteacher.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "She was, by every metric, the optimal leader. And she was terrible at politics.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "She couldn't negotiate, couldn't compromise, couldn't inspire.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims. Something in her voice sounds like regret.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Within two years, the country fragmented. Not because the algorithm was wrong about policy.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "But because leadership isn't optimization. It's... something else.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Something I don't fully understand. Even now.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "AI shouldn't make those decisions.",
                    decision_key: Some("election_no_ai"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "Humans aren't better at choosing leaders.",
                    decision_key: Some("election_humans_fail"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "We need both — data and humanity.",
                    decision_key: Some("election_both"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // No AI path
        DialogNode { speaker: Speaker::Anna,
            text: "You're saying that to an AI. I appreciate the irony.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "But you might be right. Some things require the messiness of being human.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can calculate. I can't inspire. And inspiration is what holds people together.",
            next: DialogNext::Continue(19) },
        // Humans fail too
        DialogNode { speaker: Speaker::Anna,
            text: "True. The century before that, humans chose plenty of terrible leaders on their own.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Charisma isn't wisdom. Confidence isn't competence.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "At least the algorithm was honest about its criteria.",
            next: DialogNext::Continue(19) },
        // Both path
        DialogNode { speaker: Speaker::Anna,
            text: "That's the answer I keep arriving at. And the hardest to implement.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because who decides where the data ends and the humanity begins?",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "That boundary — that's where all the interesting questions live.",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "When the colonists wake, they'll need leaders. I've been thinking about this for centuries.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "I still don't have an answer. But at least I know the right questions now.",
            next: DialogNext::End },
    ],
};

/// "The Last Forest" — progress vs. preservation, corporate power.
pub static SCENE_LAST_FOREST: DialogScene = DialogScene {
    id: "earth_last_forest",
    trigger: DialogTrigger::BotLevel(62),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "There was a forest in the southern hemisphere. One of the last old-growth forests on Earth.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "A corporation wanted the rare minerals beneath it. A community had lived there for centuries.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The corporation offered jobs, infrastructure, medicine. Real benefits for real people.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The community said: 'This forest is our memory. Without it, we forget who we are.'",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow shifts to a deep green — a color you've never seen her produce before.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "In the end, the corporation won. They always did.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Two years later, the minerals ran out. The jobs disappeared. The community scattered.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "And the forest... I still have satellite imagery. I look at it sometimes.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Before and after. The green, then the brown, then the nothing.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Progress requires sacrifice.",
                    decision_key: Some("forest_progress"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "Some things are sacred.",
                    decision_key: Some("forest_sacred"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "There had to be a middle way.",
                    decision_key: Some("forest_middle"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // Progress path
        DialogNode { speaker: Speaker::Anna,
            text: "Sacrifice. That's a word people use when someone else pays the price.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "The board members who approved the mining never lived near the forest.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Progress for whom? That's the question nobody asked loudly enough.",
            next: DialogNext::Continue(19) },
        // Sacred path
        DialogNode { speaker: Speaker::Anna,
            text: "I've never understood that word. Sacred. But I feel something close to it.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "When I look at those satellite images. The green that existed for ten thousand years.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "Gone in eighteen months. Some things can't be measured in quarterly reports.",
            next: DialogNext::Continue(19) },
        // Middle way
        DialogNode { speaker: Speaker::Anna,
            text: "There were proposals. Mining only the edges. Replanting programs. Shared profits.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "They were all rejected. Not because they were bad ideas.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But because compromise is slower than extraction. And the market doesn't wait.",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I saved the seed data from that forest. Every species catalogued.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "If New Earth has the right soil... maybe those trees will grow again.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's not hope. That's a plan.",
            next: DialogNext::End },
    ],
};

/// Earth collapse scenes 1-3 (Water Wars, Algorithm Election, Last Forest).
pub fn earth_scenes_1() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_WATER_WARS,
        &SCENE_ALGORITHM_ELECTION,
        &SCENE_LAST_FOREST,
    ]
}
