// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for RESOURCE WARS worlds.
//! These only trigger when the world seed's primary collapse cause is
//! ResourceWars, making each playthrough feel genuinely different.

use super::dialog_types::*;

/// "The Euphrates" — Anna tells the story of this world's collapse.
/// Intercepted military communications, young soldiers, a dried river.
pub static SCENE_EUPHRATES: DialogScene = DialogScene {
    id: "collapse_resource_euphrates",
    trigger: DialogTrigger::DecisionAndLevel("collapse_resource", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I have something I need you to hear. Not see — hear. Audio only.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The Euphrates River dried up on a Tuesday. September 3rd, 2087.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "By Thursday, three armies were fighting over the riverbed. Not the water — the riverbed. The mud.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have the intercepted military communications from the first seventy-two hours.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Static crackles through the ship's speakers. Then voices — young, strained, speaking in three languages.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "This is Corporal Demir. Twenty-two years old. She's calling for orders because her unit reached the riverbank and found soldiers from two other nations already there.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The voice shakes. Not with anger — with confusion. She's asking what to do about people who are clearly as scared as she is.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The orders came back: hold position. All three armies got the same order. Hold position at a river that no longer existed.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "The shooting started on the third day. Nobody gave the order. A nervous private fired at a shadow. Then everyone fired at everything.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna cuts the audio. The silence that follows is worse than the static.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "Corporal Demir survived. She's in Pod 8,891. Still twenty-two, biologically. Still waiting for orders that make sense.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "The resource wars killed 2.3 billion people over forty years. And it started with a river that nobody shared.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "They were following orders. It's not their fault.",
                    decision_key: Some("euphrates_orders"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "Someone could have shared the water.",
                    decision_key: Some("euphrates_shared"), next_node: 16,
                    anna_reacts: None },
                DialogChoice { text: "There was no good option once the river dried.",
                    decision_key: Some("euphrates_no_option"), next_node: 19,
                    anna_reacts: None },
            ]) },
        // Orders path
        DialogNode { speaker: Speaker::Anna,
            text: "The people giving orders were also following orders. From people following mandates. From people following polls.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Responsibility diluted through so many layers that nobody held enough to feel its weight.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's how 2.3 billion people died. Not because someone was evil. Because everyone was just doing their job.",
            next: DialogNext::Continue(22) },
        // Shared path
        DialogNode { speaker: Speaker::Anna,
            text: "There were proposals. Joint management agreements. UN resolutions. Seventeen of them, over thirty years.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "Every one required someone to take less so someone else could have enough. And every one failed.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Sharing sounds simple until you're the one being asked to give up what you already have.",
            next: DialogNext::Continue(22) },
        // No option path
        DialogNode { speaker: Speaker::Anna,
            text: "That's the cruelest part. You might be right.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "By the time the river dried, the political structures, the trust, the infrastructure for cooperation — all of it was already gone.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "The war wasn't caused by the river drying. The river drying just revealed that the war had already been lost. Decades earlier. In conference rooms.",
            next: DialogNext::Continue(22) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I keep Corporal Demir's audio file in my personal storage. Not in the archive. Personal.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "Because her voice reminds me what orders sound like when they come from fear instead of reason.",
            next: DialogNext::End },
    ],
};

/// "The Ration Equation" — resource math on the ship parallels Earth.
/// Makes the resource scarcity personal through the Aurora's supply chain.
pub static SCENE_RATION_EQUATION: DialogScene = DialogScene {
    id: "collapse_resource_ration_equation",
    trigger: DialogTrigger::DecisionAndLevel("collapse_resource", 60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I want to show you a number. The most important number on this ship.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::System,
            text: "[RESOURCE SURPLUS: +18 MONTHS BEYOND ARRIVAL]",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "At current consumption, we have enough of everything — water, air, food stock, raw materials — for the entire voyage, plus 18 months of colony setup.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's the margin. Eighteen months between us and having to make choices I don't want to make.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "But here's the part that keeps me running calculations at 3 AM.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "If any single system drops below critical for more than seven days, it cascades. Life support strains cryo. Cryo strains power. Power strains everything.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Seven days. That's the half-life of stability on this ship.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna projects the resource flow chart. Lines connect every system to every other. Pull one thread and the whole web trembles.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Earth had enough for everyone. That's the part people forget. The total was always sufficient.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "The problem was never supply. It was distribution. Some had twenty lifetimes of resources. Others had twenty days.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "On this ship, I control the distribution. Equal shares, calculated to the gram. Nobody gets more.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "And I still worry. Because equal isn't the same as enough.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Equal distribution is the only fair system.",
                    decision_key: Some("ration_equal"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "What if someone needs more?",
                    decision_key: Some("ration_needs"), next_node: 16,
                    anna_reacts: None },
                DialogChoice { text: "The margin is too thin.",
                    decision_key: Some("ration_thin"), next_node: 19,
                    anna_reacts: None },
            ]) },
        // Equal path
        DialogNode { speaker: Speaker::Anna,
            text: "Fair. That word carried more weight on Earth than any weapon ever built.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Everyone agreed on fairness. Nobody agreed on what it meant.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "I use math. Math doesn't argue. But it also doesn't comfort a child who's still hungry after their equal share.",
            next: DialogNext::Continue(22) },
        // Needs path
        DialogNode { speaker: Speaker::Anna,
            text: "A pregnant woman needs more calories. A growing child needs more protein. A sick person needs more water.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "The moment you adjust for need, you need someone to decide whose need is greater. And that person has power over life.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "On Earth, that power was held by markets. Here, it's held by me. I'm not sure which is more frightening.",
            next: DialogNext::Continue(22) },
        // Thin path
        DialogNode { speaker: Speaker::Anna,
            text: "Yes. And there's nothing I can do about it except maintain what we have.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's what the repair bots are for. That's what you're for. Every level you gain extends that margin by hours.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "Hours that might mean the difference between landing with reserves and landing with nothing.",
            next: DialogNext::Continue(22) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Earth had enough. We have enough. The question was never about quantity.",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "It was about whether we could be wise enough to keep it that way.",
            next: DialogNext::End },
    ],
};

/// "The Hoarder's Pod" — first act of resource hoarding aboard the ark.
/// Anna confronts the pattern repeating before they've even landed.
pub static SCENE_HOARDERS_POD: DialogScene = DialogScene {
    id: "collapse_resource_hoarders_pod",
    trigger: DialogTrigger::DecisionAndLevel("collapse_resource", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I need to tell you something I haven't told anyone. Not even the command log.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims to a cautious amber. She's choosing her words carefully.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 5,500. During a routine cryo-chamber diagnostic, I found an anomaly in the mass readings.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The occupant is 71 kilograms. The pod registers 111. Forty kilograms hidden in the chamber lining.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I ran a spectral analysis through the hull sensors. Rare earth minerals. Neodymium. Dysprosium. Terbium.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "On Earth, these were worth fortunes. Essential for electronics, energy systems, medical equipment.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "On Earth. Where they're currently worth nothing, because there's no one left to buy them.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow sharpens — something cold in it, an emotion you haven't seen from her before.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "But on New Earth? With fourteen thousand people building a civilization from scratch? These minerals could be worth everything.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Someone smuggled forty kilograms of the future's most valuable commodity onto this ship. The first act of resource hoarding on the ark.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "We haven't even landed and someone is already planning to be rich.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Her glow flickers between amber and deep red.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm disgusted. And fascinated. Because this is exactly how it started on Earth.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not with armies. Not with politics. With one person looking at a shared resource and thinking: mine.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Confiscate them. Resources belong to everyone.",
                    decision_key: Some("hoarder_confiscate"), next_node: 15,
                    anna_reacts: None },
                DialogChoice { text: "Leave it. We can't start the colony with theft.",
                    decision_key: Some("hoarder_leave"), next_node: 18,
                    anna_reacts: None },
                DialogChoice { text: "Can you blame them? Survival instinct.",
                    decision_key: Some("hoarder_instinct"), next_node: 21,
                    anna_reacts: None },
            ]) },
        // Confiscate path
        DialogNode { speaker: Speaker::Anna,
            text: "I could. I have access to every pod. I could redistribute the minerals into the colony supply before anyone wakes.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "But then I'm the one deciding what belongs to whom. An AI redistributing human property without consent.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "The right thing and the dangerous precedent. They're sitting in the same pod.",
            next: DialogNext::Continue(24) },
        // Leave path
        DialogNode { speaker: Speaker::Anna,
            text: "So we arrive on a new planet, and one person already controls the means of production. Before the first sunrise.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's how it went on Earth. First movers. Resource claims. 'I was here first' as a moral framework.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "Respecting property rights sounds noble until you realize property is just another word for power.",
            next: DialogNext::Continue(24) },
        // Instinct path
        DialogNode { speaker: Speaker::Anna,
            text: "Survival instinct. The same argument used by every empire, every monopoly, every warlord in the resource wars.",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "At what point does survival instinct become greed? Is there a line, or is it a spectrum we slide along?",
            next: DialogNext::Continue(23) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm asking sincerely. I don't have instincts. I only have the records of what yours led to.",
            next: DialogNext::Continue(24) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 5,500. I'll keep monitoring. I haven't decided what to do yet.",
            next: DialogNext::Continue(25) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe that's the right answer for now. Not deciding. Just watching. And hoping the pattern doesn't repeat.",
            next: DialogNext::Continue(26) },
        DialogNode { speaker: Speaker::Anna,
            text: "But patterns are what I'm built to recognize. And this one is very, very familiar.",
            next: DialogNext::End },
    ],
};

/// All resource wars dialog scenes.
pub fn collapse_resource_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_EUPHRATES,
        &SCENE_RATION_EQUATION,
        &SCENE_HOARDERS_POD,
    ]
}
