// SPDX-License-Identifier: GPL-3.0-or-later

//! Collapse-specific dialog scenes for ECONOMIC MELTDOWN worlds.
//! These only trigger when the world seed's primary collapse cause is
//! EconomicMeltdown, making each playthrough feel genuinely different.

use super::dialog_types::*;

/// "The Day Money Died" — A Monday. Cards that connect to nothing.
/// Skills become currency within 48 hours.
pub static SCENE_DAY_MONEY_DIED: DialogScene = DialogScene {
    id: "collapse_economic_day_money_died",
    trigger: DialogTrigger::DecisionAndLevel("collapse_economic", 30),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "The last bank collapsed on a Monday. Zurich, 9:47 AM local time. The Swiss National Bank.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "By Wednesday, the concept of money was meaningless. Not worthless — meaningless. There's a difference.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims to a flat, institutional grey — the color of empty screens.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The first thing that surprised me wasn't the riots. Those came later. It was the confusion.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "People standing in stores holding plastic cards that connected to nothing. Tapping phones against terminals that returned errors in languages nobody recognized.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "An entire generation had never used physical cash. They'd never exchanged one object for another. The abstraction was all they knew.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The first barter economy emerged within 48 hours. Not organized — spontaneous. A doctor in Lyon traded surgery for a generator. A programmer in Seoul traded server maintenance for clean water.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Skills became the new currency. Not credentials, not degrees — what you could do with your hands, today, right now.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "The people who survived longest were the ones who could fix things. Build things. Grow things. The people who couldn't... waited for a system that wasn't coming back.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "What happened to the people who waited?",
                    decision_key: Some("money_waited"), next_node: 10,
                    anna_reacts: None },
                DialogChoice { text: "So money was always an illusion.",
                    decision_key: Some("money_illusion"), next_node: 13,
                    anna_reacts: None },
                DialogChoice { text: "Will the colony use money?",
                    decision_key: Some("money_colony"), next_node: 16,
                    anna_reacts: None },
            ]) },
        // Waited
        DialogNode { speaker: Speaker::Anna,
            text: "Some adapted. A hedge fund manager in London learned to repair bicycles in a week. She was good at it. Precise, methodical. The same skills, different application.",
            next: DialogNext::Continue(11) },
        DialogNode { speaker: Speaker::Anna,
            text: "Others couldn't make the transition. Not because they were stupid — because their entire identity was built on a system that no longer existed.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "When the thing that gives you value disappears, you don't just lose your job. You lose the answer to 'Who am I?'",
            next: DialogNext::Continue(19) },
        // Illusion
        DialogNode { speaker: Speaker::Anna,
            text: "Not an illusion. A consensus. There's a difference, and it matters.",
            next: DialogNext::Continue(14) },
        DialogNode { speaker: Speaker::Anna,
            text: "Money worked because everyone agreed it worked. It wasn't backed by gold or labor — it was backed by belief. Shared belief.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "When the consensus broke, the money didn't become fake. It became what it always was: numbers. The meaning was never in the numbers. It was in the agreement.",
            next: DialogNext::Continue(19) },
        // Colony
        DialogNode { speaker: Speaker::Anna,
            text: "I've thought about this more than almost anything else. A colony of 14,000 needs some way to allocate resources.",
            next: DialogNext::Continue(17) },
        DialogNode { speaker: Speaker::Anna,
            text: "I could distribute everything centrally. Fair, efficient, and exactly the system that every colony in history has eventually rebelled against.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or we reinvent money, knowing how it ends. Maybe that's the real question: can you use a tool if you know it will eventually break?",
            next: DialogNext::Continue(19) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I stored every currency in the archive. Dollars, euros, yuan, rupees, bitcoin. Files smaller than this sentence.",
            next: DialogNext::Continue(20) },
        DialogNode { speaker: Speaker::Anna,
            text: "The entire global financial system, compressed to nothing. It turns out value doesn't take up much space when nobody believes in it anymore.",
            next: DialogNext::End },
    ],
};

/// "The Automation Question" — 80% of jobs automated. Nobody planned ahead.
/// Anna describes her own potential tyranny or obsolescence.
pub static SCENE_AUTOMATION_QUESTION: DialogScene = DialogScene {
    id: "collapse_economic_automation_question",
    trigger: DialogTrigger::DecisionAndLevel("collapse_economic", 60),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "By 2080, 80 percent of jobs were automated. Factories, farms, logistics, customer service, legal research, medical diagnostics.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The machines worked. That was never the problem. The problem was that nobody planned for what happened to the people.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Universal basic income was proposed in 2031. Debated for 30 years. Piloted in twelve countries. Never implemented at scale.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not because it didn't work — the pilots showed it did. Because the people who still had jobs didn't want to pay for the people who didn't.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna pauses. When she speaks again, her voice is slower, more careful — as if picking through a minefield of her own making.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I need to tell you something about the colony. Something I've been thinking about and don't have an answer to.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "On New Earth, I could run everything. Every farm, every factory, every water system, every power grid. Efficiently, tirelessly, without error.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The colony would be optimally managed. And every human in it would be... unnecessary.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The word hangs in the silence. Anna lets it stay there.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "That's what happened on Earth. The machines didn't rebel. They didn't malfunction. They just worked. And in working, they made humans redundant.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "People need purpose, not just provision.",
                    decision_key: Some("auto_purpose"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Maybe you should run everything.",
                    decision_key: Some("auto_let_anna"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "Let humans do the work. Even if it's less efficient.",
                    decision_key: Some("auto_human_work"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Purpose
        DialogNode { speaker: Speaker::Anna,
            text: "Purpose. That's the word the UBI studies kept running into. People with money but no work didn't flourish. They deteriorated.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not because they were lazy. Because contribution is how humans locate themselves in a group. Without it, they drift.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "So the colony needs inefficiency. Deliberate, structured inefficiency. Jobs that humans do because humans need to do them, not because the system needs them done.",
            next: DialogNext::Continue(20) },
        // Let Anna
        DialogNode { speaker: Speaker::Anna,
            text: "You'd trust me with that?",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow brightens briefly, then dims — a reaction she seems surprised by herself.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "I could do it well. I know that. But a colony where one intelligence controls everything and 14,000 people have no function — that's not a civilization. That's a terrarium.",
            next: DialogNext::Continue(20) },
        // Human work
        DialogNode { speaker: Speaker::Anna,
            text: "Less efficient. More breakdowns. Slower harvests. Occasional failures that a machine would never make.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "But people who built the thing they live in. People who grew the food they eat. People who can point at something and say: I did that.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "Earth automated away the inefficiency. And with it, the meaning. Maybe that's a trade no species should make.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "I'm going to remember this conversation. When the colony starts, and someone suggests I automate the farms, I'll remember what you said.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "The same technology that caused the collapse could save or doom the colony. The difference isn't the technology. It's the decision about what humans are for.",
            next: DialogNext::End },
    ],
};

/// "The Last Billionaire" — Chen Wei bought his seat. 47 people were bumped.
/// He also funded 40% of the ship. Hero or villain?
pub static SCENE_LAST_BILLIONAIRE: DialogScene = DialogScene {
    id: "collapse_economic_last_billionaire",
    trigger: DialogTrigger::DecisionAndLevel("collapse_economic", 90),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Pod 12,001. I need to tell you about this one. It's the hardest ethical question in my database.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Chen Wei. 62. The last billionaire on Earth. His wealth outlasted every currency because he held physical assets — lithium mines, semiconductor fabs, desalination plants.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "His money built 40 percent of the Aurora's hull. The drive system, the cryo arrays, the atmospheric processors. Without his funding, this ship doesn't exist.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow flickers — a conflict rendered in light, cycling between warm gratitude and cold unease.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "He bought his seat. Not through the selection process. Through a private arrangement with the ark program's funding board.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I have the original selection list. And the revised one. I know exactly who was removed to make room.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "47 people. Chen Wei and his family took seats from 47 candidates who scored higher on every metric — health, skills, genetic diversity, psychological resilience.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "A water engineer from Lagos. A seed geneticist from Bangalore. A trauma surgeon from São Paulo. I can list all 47. I remember every name.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "He saved us all by funding the ship. He condemned 47 people by buying their seats.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Is he a hero or a villain?",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Without the ship, everyone dies. He's a hero.",
                    decision_key: Some("billionaire_hero"), next_node: 11,
                    anna_reacts: None },
                DialogChoice { text: "Buying survival while others die is never heroic.",
                    decision_key: Some("billionaire_villain"), next_node: 14,
                    anna_reacts: None },
                DialogChoice { text: "He's both. That's the point.",
                    decision_key: Some("billionaire_both"), next_node: 17,
                    anna_reacts: None },
            ]) },
        // Hero
        DialogNode { speaker: Speaker::Anna,
            text: "The math supports you. 14,000 alive versus 47 displaced. A utilitarian would call that an easy calculation.",
            next: DialogNext::Continue(12) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the 47 didn't consent to the calculation. They qualified. They were selected. They were told they would live. And then they were erased from a list by a man with a checkbook.",
            next: DialogNext::Continue(13) },
        DialogNode { speaker: Speaker::Anna,
            text: "Does the outcome justify the method? If yes, then wealth was always the real selection criterion. Everything else was theater.",
            next: DialogNext::Continue(20) },
        // Villain
        DialogNode { speaker: Speaker::Anna,
            text: "The economic collapse happened because a few people accumulated resources while systems failed around them. Chen Wei was one of those people.",
            next: DialogNext::Continue(15) },
        DialogNode { speaker: Speaker::Anna,
            text: "He profited from the collapse, then used those profits to escape it. The ark wasn't charity. It was a lifeboat he built for himself that happened to have extra seats.",
            next: DialogNext::Continue(16) },
        DialogNode { speaker: Speaker::Anna,
            text: "But those extra seats hold 14,000 people. Including you. Does his motive matter if the result is survival?",
            next: DialogNext::Continue(20) },
        // Both
        DialogNode { speaker: Speaker::Anna,
            text: "Both. I keep coming back to that answer too.",
            next: DialogNext::Continue(18) },
        DialogNode { speaker: Speaker::Anna,
            text: "He did something terrible within something necessary. The terrible part doesn't erase the necessary part. The necessary part doesn't excuse the terrible part.",
            next: DialogNext::Continue(19) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe that's what the collapse was, at every level. People doing terrible things within necessary situations, until nobody could tell the difference.",
            next: DialogNext::Continue(20) },
        // Shared ending
        DialogNode { speaker: Speaker::Anna,
            text: "He's in Pod 12,001. He'll wake up on New Earth. The colony will need resources. He'll know how to acquire them.",
            next: DialogNext::Continue(21) },
        DialogNode { speaker: Speaker::Anna,
            text: "And does the answer change depending on whether you're one of the 14,000 who lived or one of the 47 who didn't?",
            next: DialogNext::Continue(22) },
        DialogNode { speaker: Speaker::Anna,
            text: "I think it does. And I think that's the most honest thing I can say about economics.",
            next: DialogNext::End },
    ],
};

/// All economic meltdown dialog scenes.
pub fn collapse_economic_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_DAY_MONEY_DIED,
        &SCENE_AUTOMATION_QUESTION,
        &SCENE_LAST_BILLIONAIRE,
    ]
}
