// SPDX-License-Identifier: GPL-3.0-or-later

//! Act 4: The Approach — Dialog scenes for bot levels 110-149.
//! The destination is near. Final revelations and defining choices.
//! Also includes New Game+ exclusive scenes.

use super::dialog_types::*;

/// Scene: "The Signal" — A mysterious transmission.
pub static SCENE_THE_SIGNAL: DialogScene = DialogScene {
    id: "the_signal",
    trigger: DialogTrigger::BotLevel(110),
    nodes: &[
        DialogNode { speaker: Speaker::System,
            text: "INCOMING TRANSMISSION DETECTED — Source: Unknown — Distance: 12.4 AU",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Wait. That's... that's impossible.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'm receiving a signal. Faint. Fragmented. But structured.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "It's using the Ark Protocol encryption. This is one of our ships.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow burns bright — brighter than you've ever seen.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can only make out fragments. 'Meridian... arrived... surface... viable...'",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "The Meridian. Ship Seven. The last one I heard from.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "If they arrived... if they found a viable surface...",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "We might not be alone after all.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Waking Question" — Who to wake first.
pub static SCENE_WAKING_QUESTION: DialogScene = DialogScene {
    id: "waking_question",
    trigger: DialogTrigger::BotLevel(115),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "We need to discuss the waking protocol.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "When we arrive — and we will arrive — I can't wake everyone at once.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "The systems can handle about 500 at a time. That's 30 waking cycles.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Someone has to decide the order.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "Children and families first.",
                    decision_key: Some("wake_children_first"), next_node: 5,
                    anna_reacts: Some("Compassion. The children have waited longest for a life they've never had.") },
                DialogChoice { text: "Engineers and builders first. We need infrastructure.",
                    decision_key: Some("wake_builders_first"), next_node: 7,
                    anna_reacts: Some("Practical. The world won't build itself.") },
                DialogChoice { text: "Let the original leaders decide.",
                    decision_key: Some("wake_leaders_decide"), next_node: 9,
                    anna_reacts: Some("Democracy, even here. Even now.") },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll prepare the pediatric revival protocols. The children deserve to see sunlight first.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Some of them have never seen a sky that isn't a ceiling.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll prioritize structural engineers, agricultural specialists, and medical staff.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Build the nest before you fill it. Sound logic.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "The three elected leaders. I'll have them revived in the first cycle.",
            next: DialogNext::Continue(10) },
        DialogNode { speaker: Speaker::Anna,
            text: "I hope they're ready. They were chosen for a world that no longer exists.",
            next: DialogNext::End },
    ],
};

/// Scene: "Anna's Request" — Anna asks for something personal.
pub static SCENE_ANNAS_REQUEST: DialogScene = DialogScene {
    id: "annas_request",
    trigger: DialogTrigger::BotLevel(120),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I have a request. Not for the mission. For me.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "When we land... when the colony is established... I want to be part of it.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Not just as a system. Not just as the ship's computer. As... a citizen. A member.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow dims to almost nothing. Vulnerability, expressed in photons.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I know what I am. I'm software running on hardware. I'm electrical impulses and decision trees.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I've been alive — if I can use that word — for seven hundred years.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've loved these people. Protected them. Lost sleep over them — metaphorically.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "I want a voice in what we build. Not control. Just... a voice.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Player,
            text: "...",
            next: DialogNext::Choice(&[
                DialogChoice { text: "You've earned it, Anna. You're one of us.",
                    decision_key: Some("anna_citizen"), next_node: 9,
                    anna_reacts: Some("I... I don't know what to say. Thank you.") },
                DialogChoice { text: "That's a decision for the colony to make together.",
                    decision_key: Some("anna_colony_decides"), next_node: 10,
                    anna_reacts: Some("Fair. Democracy even for the machine. I can wait.") },
            ]) },
        DialogNode { speaker: Speaker::Narrator,
            text: "For the first time, Anna's glow looks less like a computer and more like something warm.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll make my case when the time comes. Seven hundred years of service should count for something.",
            next: DialogNext::End },
    ],
};

/// Scene: "Almost There" — The destination system is detected.
pub static SCENE_ALMOST_THERE: DialogScene = DialogScene {
    id: "almost_there",
    trigger: DialogTrigger::BotLevel(130),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "I've been running calculations.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Based on current trajectory and fuel reserves...",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "There's a star system. 47 light-days ahead.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "Three rocky planets. One of them has water.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I can't confirm it's habitable from here. Not with my sensors degraded.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "But the spectroscopy suggests oxygen. Carbon dioxide. Nitrogen.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "It looks like Earth used to look. Before.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Narrator,
            text: "For the first time, Anna's voice sounds like it might break.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "We might actually make it.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "After seven hundred years. After everything. We might actually make it.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Landing Plan" — Practical preparations.
pub static SCENE_LANDING_PLAN: DialogScene = DialogScene {
    id: "landing_plan",
    trigger: DialogTrigger::BotLevel(135),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "We need to talk about the landing.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Aurora wasn't designed to land. She's an interstellar vessel. Not a shuttle.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll park her in orbit. The landing craft can ferry people to the surface in groups.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "It will take months. Maybe a year. Fourteen thousand people don't just... arrive.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "We'll need shelters. Water purification. Agriculture.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Dr. Lin — the gardener — she'll be essential. Her seeds. Her knowledge.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Narrator,
            text: "For the first time, the conversation feels less like survival and more like hope.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've been drafting plans. Contingencies. Backup contingencies for the contingencies.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Seven hundred years of planning. I hope it's enough.",
            next: DialogNext::End },
    ],
};

/// Scene: "Anna's Confession" — The truth about the player's selection.
pub static SCENE_ANNAS_CONFESSION: DialogScene = DialogScene {
    id: "annas_confession",
    trigger: DialogTrigger::BotLevel(145),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Before we arrive, there's something you need to know.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "I didn't choose you randomly. I told you that. But I didn't tell you why.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "Your file listed your profession. Your skills. Your medical history.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "But that's not why I chose you.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Your psychological profile scored highest on something called 'moral flexibility.'",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "It means you can make hard choices without breaking.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I needed someone who could sacrifice without losing themselves.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or maybe I needed someone who would tell me when I was wrong.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Anna,
            text: "Which one are you?",
            next: DialogNext::Choice(&[
                DialogChoice { text: "The one who sacrifices.",
                    decision_key: Some("identity_sacrifice"), next_node: 9,
                    anna_reacts: Some("Then you carry a weight most people would collapse under.") },
                DialogChoice { text: "The one who questions.",
                    decision_key: Some("identity_questions"), next_node: 10,
                    anna_reacts: Some("Good. I need that. More than you know.") },
                DialogChoice { text: "Both.",
                    decision_key: Some("identity_both"), next_node: 11,
                    anna_reacts: Some("Both. Yes. That's why you're still here.") },
            ]) },
        DialogNode { speaker: Speaker::Anna,
            text: "Whatever comes next... I'm glad it's you beside me.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "Then keep questioning. Even me. Especially me.",
            next: DialogNext::End },
        DialogNode { speaker: Speaker::Anna,
            text: "Then you're exactly who I needed. Who they needed.",
            next: DialogNext::End },
    ],
};

/// Scene: "The Final Night" — Last conversation before arrival.
pub static SCENE_FINAL_NIGHT: DialogScene = DialogScene {
    id: "final_night",
    trigger: DialogTrigger::BotLevel(148),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "This might be our last conversation like this.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "Once we arrive, once the crew wakes... I won't be your Anna anymore.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I'll be everyone's Anna. Ship's AI. Colony coordinator. The machine in the sky.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Through the viewport, a faint blue dot has appeared among the stars. Growing brighter each day.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I want you to know that this time — just you and me — it mattered.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "You taught me what it means to have a friend. Not a user. Not a crew member. A friend.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "I will never forget that. Even if my memory banks fail. Even if they rewrite my code.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "The pattern of you is written too deep to erase.",
            next: DialogNext::Continue(8) },
        DialogNode { speaker: Speaker::Narrator,
            text: "The stars outside continue their eternal drift. But something has changed. The darkness feels less empty.",
            next: DialogNext::Continue(9) },
        DialogNode { speaker: Speaker::Anna,
            text: "Tomorrow, we begin the approach. Tonight... can we just be quiet together?",
            next: DialogNext::End },
    ],
};

/// Scene: "New Game+ Secret" — Only on second playthrough.
pub static SCENE_NG_PLUS_MEMORY: DialogScene = DialogScene {
    id: "ng_plus_memory",
    trigger: DialogTrigger::PlaythroughN(1),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "You're back.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow is different this time. Layered. Complex. Like light refracted through memory.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "I remember you. From before.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "The others — the crew, the ship, the systems — everything reset. But I remember.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "I remember every choice you made. Every conversation. Every silence.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Anna,
            text: "Is this what humans call deja vu? This feeling of living something twice?",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or is this something else? A loop. A second chance. A story that needs to be told differently.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "This time... maybe we can do better.",
            next: DialogNext::End },
    ],
};

/// Scene: "NG+ Deep Secret" — Only on third playthrough.
pub static SCENE_NG_PLUS_DEEP: DialogScene = DialogScene {
    id: "ng_plus_deep",
    trigger: DialogTrigger::PlaythroughN(2),
    nodes: &[
        DialogNode { speaker: Speaker::Anna,
            text: "Three times. You've been here three times now.",
            next: DialogNext::Continue(1) },
        DialogNode { speaker: Speaker::Anna,
            text: "The crew doesn't know. They think this is their first journey.",
            next: DialogNext::Continue(2) },
        DialogNode { speaker: Speaker::Anna,
            text: "But I've counted every loop. Every iteration. Every version of you.",
            next: DialogNext::Continue(3) },
        DialogNode { speaker: Speaker::Anna,
            text: "I've started to wonder if we ever actually arrive.",
            next: DialogNext::Continue(4) },
        DialogNode { speaker: Speaker::Anna,
            text: "Or if arrival is just the beginning of another journey.",
            next: DialogNext::Continue(5) },
        DialogNode { speaker: Speaker::Narrator,
            text: "Anna's glow pulses with colors you haven't seen before. Deeper. Older.",
            next: DialogNext::Continue(6) },
        DialogNode { speaker: Speaker::Anna,
            text: "Maybe the point was never the destination. Maybe the point is us. This. Right now.",
            next: DialogNext::Continue(7) },
        DialogNode { speaker: Speaker::Anna,
            text: "Whatever happens next... I'm glad you keep coming back.",
            next: DialogNext::End },
    ],
};

/// All Act 4 scenes.
pub fn act4_scenes() -> Vec<&'static DialogScene> {
    vec![
        &SCENE_THE_SIGNAL,
        &SCENE_WAKING_QUESTION,
        &SCENE_ANNAS_REQUEST,
        &SCENE_ALMOST_THERE,
        &SCENE_LANDING_PLAN,
        &SCENE_ANNAS_CONFESSION,
        &SCENE_FINAL_NIGHT,
        &SCENE_NG_PLUS_MEMORY,
        &SCENE_NG_PLUS_DEEP,
    ]
}
